export const CartLocators={
    cart: `//h1[contains(text(), 'Cart')]`,
    orderSummary: `//h2[contains(text(), 'Order Summary')]`,
    orderAgain: `//h2[contains(text(), 'Order Again')]`,
    retinolPrice: `//p[contains(text(), '$270.00')]`,
    pcaCustomerCareNumber: `//p[contains(text(), '877.PCA.SKIN [722.7546]')]`,
    pcaCustomerCareDaysAvailable: `//p[contains(text(), 'Available Monday – Friday')]`,
    pcaCustomerCareTimeAvailable: `//p[contains(text(), '7:00 AM – 5:00 PM AZ')]`,
    orderAgainTagline: `//p[contains(text(), 'Reorder your favorites to ensure you always have your essentials in stock!')]`,
    acneGel: `//p[contains(text(), 'Acne Gel with OmniSome®')]`,
    acneCream: `//p[contains(text(), 'Acne Cream')]`,
    pureRetinolPeel: `//p[contains(text(), '6% Pure Retinol Peel')]`,
    retinolPeel: `//p[contains(text(), '4% Retinol Peel')]`,
    viewingNumberOfCourses: `//p[contains(text(), 'Viewing 79 out of 79 courses')]`,
    orderItemNumber: `//span[contains(text(), 'item# 11277')]`,
    favouriteNotSelected: `//span[contains(text(), 'Favorite not selected')]`,
    estimatedShipping: `//span[contains(text(), 'Item Subtotal: $270.00')]`,
    calculatedAtCheckout: `//span[contains(text(), 'Calculated at checkout')]`,
    estimatedTax: `//span[contains(text(), 'Estimated Tax')]`,
    checkout: `(//span[contains(text(), 'Checkout')])[1]`,
    pureRetinolPrice: `//p[contains(text(), '$320.00')]`,
    price: `//span[contains(text(), '$9.50-$32.00')]`,
    bestSellerLable: `//span[contains(text(), 'Best-seller')]`,
    itemQuantityLable: `//div[@class="relative qty-selector-wrapper w-auto current-1 min-1"]//label[contains(text(), 'Item Quantity')]`,
    applyButton: `//button[contains(text(), 'Apply')]`,

    orderAgainProductPrice:`div.more-to-explore-carousel:has-text('Order Again') div.product-card-main-wrapper:has-text('Acne Cream') div.price-wrapper`, // Change the product name to locate another product
    orderAgainProductAddToCart:`div.more-to-explore-carousel:has-text('Order Again') div.product-card-main-wrapper:has-text('Acne Cream') button`,
    orderAgainProductSelectSize:`div.more-to-explore-carousel:has-text('Order Again') div.product-card-main-wrapper:has-text('Acne Gel with OmniSome®') a:has-text('Select Size')`,
    increaseProductCount:`div.cart-item-section:has-text('Acne Cream') span.increase-icon`,
    productCount:`div.cart-item-section:has-text('Acne Cream') input`,
    maximumQtyReachedToast:`//div[@id="add-to-cart-api-error"]`,
    maximunQtyReachedCloseBtn:`//div[@id="add-to-cart-api-error"]//button`,
    cartItemSection:`div.cart-item-section`,
    placeOrder : `(//button[span[text()="Place Order"]])[1]`,
    thankYouForOrder : `//div[contains(text(),"Thank You For Your Order!")]`
}