    export const CheckoutLocators={
        
        checkOutTab:`('button', { name: 'Checkout' })`,
        checkOutInBlue:`('Checkout')`,
        shipping:`('heading', { name: 'Shipping', exact: true })`,
        address:`//div[@class='h-[var(--address-card-height-desk)] lg:w-[var(--address-card-width-desk)] w-[var(--address-card-width-mob)] relative flex shadow-lg p-6 border-tertiary-100 border-2']`,
        shippingMethod:`('heading', { name: 'Shipping Method' })`,
        dropship:`('ShippingThis is a dropship')`,
        billingAdd:`('BillingAdd New Payment MethodCard ending in 4242Exp 12/2030Billing Address24')`,
        billingBox:`//div[@class='col-span-12 lg:col-start-1 lg:col-end-9 border border-tertiary-400 p-5 mb-6']`,
        cardEndingBox:`('div:nth-child(2) > .gap-5')`,
        emailAddress:`('heading', { name: 'Email Address' })`,
        email:`('div').filter({ hasText: /^bp_esha_shah\+all@colpal\.com$/ })`,
        yourCart:`('heading', { name: 'Your Cart' })`,
        items:`//p[@class='inline text-base font-light leading-6 total-items']`,
        editCart:`//button[@aria-label='Edit Cart Your Cart']`,
        showAll:`('button', { name: 'Show All' })`,
        yourCartItems:`('Your Cart(3 items)Edit Cart6')`,
        showLess:`('button', { name: 'Show Less' })`,
        orderSummaryWholeBox:`//div[@class='col-span-12 lg:col-end-13 lg:col-span-4 order-summary-cust-serv-wrapper']`,
        oderSummary:`('heading', { name: 'Order Summary' })`,
        orderSummaryWholeBoxWithPlaceOrder:`//*[@id="skipNavigation"]/div/section/div/div[2]/div[1]`,
        subTotal:`('Subtotal')`,
        estimatedShipping:`//span[normalize-space()='Estimated Shipping']`,
        estimatedTax:`//span[normalize-space()='Estimated Tax']`,
        estimatedTotal:`//div[contains(@class,'leading-7 total-text')]`,
        accurateTotalWillBeCalculatedOnFinalInvoice:`//div[@class='flex items-center justify-center h-10 text-sm bg-tertiary-100 text-tertiary-400']`,
        apply:`//input[@placeholder='Add promo code']`,
        placeOrder:`//div[@class='py-6 mt-4 border border-x-0 border-b-0 order-btn-wrapper']//button[@type='button']`,
        pcaSKINCustomerSupport:`//h3[contains(@class,'heading')]`,
        supportNumber:`//p[contains(@class,'text-xl font-light leading-7 customer-support-number')]`,
        availableMondayFriday:`//p[@class='font-light availability-day']`,
        time:`//p[@class='font-light availability-time']`,
    }