export const FavouritesLocators = {

    favoritesHeader: "//div[normalize-space()='Favorites']",
    productsButton: "//button[contains(@aria-label,'Products selected')]",
    coursesButton: "//button[contains(@aria-label,'Courses unselected')]",
    productsButtonUnselected: "//button[@aria-label=' Products unselected']",
    acneGelWithOmnisomeProduct: "//p[@title='Acne Gel with OmniSome®']//ancestor::div[@class='relative col-span-12 lg:col-span-4 product-list']",
    acneGelWithOmnisomeProductRatings: "//a[@id='ed3f98ae-a43f-45b1-b9b6-f00b1ee43890' and @class='bv_main_container bv_hover bv_inline_rating_container_left']",
    acneGelWithOmnisomeTitle: "//p[@title='Acne Gel with OmniSome®' and @class='mt-4 text-tertiary-400 product-name line-clamp-2 font-regular h-auto lg:h-[var(--plp-card-title-height)] title-wrapper']",
    acneGelWithOmnisomePriceRange: "//span[text()='$9.50-$32.00']",
    acneGelWithOmnisome2sizes: "//p[@title='Acne Gel with OmniSome®']//ancestor::div[@class='relative col-span-12 lg:col-span-4 product-list']//span[@class='text-base font-regular']",
    removeFromFavorites: "(//button[contains(@class, 'remove-favorite-cta') and contains(@class, 'text-primary-400')])",
    addToCart: "//div[contains(@aria-label,'/ 0.5 oz.')]//button[contains(@aria-label,'Add to Cart')][normalize-space()='Add to Cart']",
    acneCreamProduct: "//p[@title='Acne Cream']//ancestor::div[@class='relative col-span-12 lg:col-span-4 product-list']",
    acneProductRatings: "//a[contains(@class, 'bv_main_container') and contains(@aria-label, '3.7 out of 5 stars')]",
    acneCreamPriceRange: "//span[text()='$20.00']",
    acneCreamTitle: "//p[contains(@class, 'product-name') and contains(@title, 'Acne Cream')]",
    acneCreamQty: "//p[@title='Acne Cream']//ancestor::div[@class='relative col-span-12 lg:col-span-4 product-list']//span[@class='text-base font-regular']",
    bodyTherapyProduct: "//p[@title='Body Therapy']//ancestor::div[@class='relative col-span-12 lg:col-span-4 product-list']",
    bodyTherapyProductPriceRange: "//span[text()='$6.50-$36.00']",
    bodyTherapyQty: "//p[@title='Body Therapy']//ancestor::div[@class='relative col-span-12 lg:col-span-4 product-list']//span[@class='text-base font-regular']",
    antiRednessSerumProduct: "//p[@title='Anti-Redness Serum']//ancestor::div[@class='relative col-span-12 lg:col-span-4 product-list']",
    antiRednessSerumProductPriceRange: "//span[text()='$35.00']",
    antiRednessSerumProductQty: "//p[@title='Anti-Redness Serum']//ancestor::div[@class='relative col-span-12 lg:col-span-4 product-list']//span[@class='text-base font-regular']",
    cAndEHandRenewalProduct: "//p[@title='C&E Hand Renewal']//ancestor::div[@class='relative col-span-12 lg:col-span-4 product-list']",
    cAndEHandRenewalProductPriceRange: "//span[text()='$41.00']",
    cAndEHandRenewalProductQty: "//p[@title='C&E Hand Renewal']//ancestor::div[@class='relative col-span-12 lg:col-span-4 product-list']//span[@class='text-base font-regular']",
    coursesButtonSelected: "//button[@aria-label=' Courses selected']",
    coursesButtonUnselected: "//button[@aria-label=' Courses unselected']",
    aDeepDiveIntoProfessionalProductsCourse: "//a[@aria-label='A Deep Dive Into Professional Products']//img[@class='object-cover']",
    aDeepDiveIntoProfessionalProductsCourseHeader: "//h2[normalize-space()='A Deep Dive Into Professional Products']",
    courseRating: "//a[contains(@class, 'bv_main_container')]",
    aDeepDiveIntoProfessionalProductsDetails: "//p[contains(text(),'Expand your treatment plans and options for your p')]",
    pcaSkin: "//p[contains(text(),'Expand your treatment plans and options for your p')]//strong[contains(text(),'PCA SKIN')]",
    learnMore: "//a[contains(@aria-label,'Learn More A Deep Dive Into Professional Products')]",
    courseRemoveFromFavorites: "//div[contains(@aria-label,'A Deep Dive Into Professional Products')]//button[contains(@type,'button')]//div[2]",
    enhancingStudentCurriculumCourse: "//a[contains(@aria-label,'Enhancing Student Curriculum')]//img[contains(@class,'object-cover')]",
    enhancingStudentCurriculumCourseHeader: "//h2[normalize-space()='Enhancing Student Curriculum']",
    enhancingStudentCurriculumCourseDetails: "//p[contains(text(),'These online courses have been curated to further ')]",
    enhancingStudentCurriculumCourseLearnMore: "//a[contains(@aria-label,'Learn More  Enhancing Student Curriculum')]",

    collagenHydratorProduct: `div.product-card-main-wrapper:has-text('Collagen Hydrator')`,
    sixPerPureRetinolPeel: `div.product-card-main-wrapper:has-text('6% Pure Retinol Peel')`,
    hyaluronicAcidOvernightMaskProduct: `div.product-card-main-wrapper:has-text('Hyaluronic Acid Overnight Mask')`,
    collagenHydratorPrice: `div.product-card-main-wrapper:has-text('Collagen Hydrator') div.price-wrapper`,
    sixPerPureRetinolPeelPrice: `div.product-card-main-wrapper:has-text('6% Pure Retinol Peel') div.price-wrapper`,
    collagenHydratorRemovefavouriteBtn: `div.product-card-main-wrapper:has-text('Collagen Hydrator') button.remove-favorite-cta`,
    sixPerPureRetinolPeelRemovefavouriteBtn: `div.product-card-main-wrapper:has-text('6% Pure Retinol Peel') button.remove-favorite-cta`,
    collagenHydratorSelectSizeBtn: `div.product-card-main-wrapper:has-text('Collagen Hydrator') a:has-text('Select Size')`,
    hyaluronicAcidOvernightMaskAddToCartBtn: `div.product-card-main-wrapper:has-text('Hyaluronic Acid Overnight Mask') button:has-text('Add to Cart')`,
    sixPerPureRetinolPeelAddToCartBtn: `div.product-card-main-wrapper:has-text('6% Pure Retinol Peel') button:has-text('Add to Cart')`,
    sixPerPureRetinolPeelSelectSize: `div.product-card-main-wrapper:has-text('6% Pure Retinol Peel') a:has-text('Select Size')`,
    maximumQtyReachedToast: `//div[@id="add-to-cart-api-error"]//div[contains(text(),'Maximum Quantity Reached')]`,
    maximunQtyReachedCloseBtn: `//div[@id="add-to-cart-api-error"]//button`,
    favouriteRestrictedMessageUAT: `div.product-card-main-wrapper:has-text('6% Pure Retinol Peel') div:has-text('Apologies, you cannot purchase this product.')`,
    pigmentCorrectPeelRemovefavouriteBtn: `div.product-card-main-wrapper:has-text('Pigment Correct Peel') button.remove-favorite-cta`,
    dualActionRednessReliefRemovefavouriteBtn: `div.product-card-main-wrapper:has-text('Dual Action Redness Relief') button.remove-favorite-cta`,
    removedFromFavouriteToast: `//div[@id="remove-from-favorite-api-sucess"]`,

    shopCoursesBtn: `div.no-favorites-container a`,
    aDeepDiveIntoProfProductsRemoveFav: `div.favorite-course div.course-card-content-wrapper:has-text('A Deep Dive Into Professional Products') button`,
    aPhysiciansPointofViewRemoveFav: `div.favorite-course div.course-card-content-wrapper:has-text('A Deep Dive into Sensitive Skin and Treatment') button`,

}