export const HomePageLocators = {
  shopByPatientConditionMenuText: '//a[contains(text(), "Shop By Patient Condition") and contains(@class, "menu-title")]',
  toothbrushMenuText: '//a[contains(text(), "Toothbrushes") and contains(@class, "menu-title")]',
  acceptCookiesButton: '//button[contains(@id, "truste-consent-button")]',
  softSubMenuLocatorText: 'li.navigation-filter-options a[title="Soft"]',
  toothbrushSubmenuWrapperText: '//div[contains(@id, "navigation-submenu-wrapper-2")]',
  colgateBadgeImageText: '//img[@alt="Colgate Palmolive"]',
  oralRinsesMenuText: '//a[contains(text(), "Oral Rinses") and contains(@class, "menu-title")]',
  oralRinsesSubMenuWrapperText: '//div[contains(@id, "navigation-submenu-wrapper-6")]',
  colgatePerioGardRinseSubMenuLocatorText: '//a[@href="/products?category=Oral%20Rinses&category-2=colgate--periogard-rinse"]',
  oralRinsesHeadingText: '//div[contains(@class, "heading") and contains(text(), "Oral Rinses")]',
  shopByPatientConditionText: `nav li a:text-is('Shop By Patient Condition')`,
  sensitivityButton: `div.navigation-submenu-container a span:text-is('Sensitivity')`,
  orthoButton: `div.navigation-submenu-container a span:text-is('Ortho')`,
  gingivitisOrPerioButton: `div.navigation-submenu-container a span:text-is('Gingivitis / Perio')`,
  cariesButton: `div.navigation-submenu-container a span:text-is('Caries')`,
  whiteningButton: `div.navigation-submenu-container a span:text-is('Whitening')`,
  erosionButton: `div.navigation-submenu-container a span:text-is('Erosion')`,
  dryMouthButton: `div.navigation-submenu-container a span:text-is('Dry Mouth')`,
  sensitivityAppliedFilterButton: `button div.text-sm:text-is('Sensitivity')`,
  orthoButtonAppliedFilterButton: `button div.text-sm:text-is('Ortho')`,
  gingivitisOrPerioButtonAppliedFilterButton: `button div.text-sm:text-is('Gingivitis/Perio')`,
  cariesButtonAppliedFilterButton: `button div.text-sm:text-is('Caries Adult')`,
  whiteningButtonAppliedFilterButton: `button div.text-sm:text-is('Whitening')`,
  erosionButtonAppliedFilterButton: `button div.text-sm:text-is('Erosion')`,
  dryMouthButtonAppliedFilterButton: `button div.text-sm:text-is('Dry Mouth')`,
  softButtonAppliedFilterButton: `button div.text-sm:text-is('Soft')`,
  ultraSoftButtonAppliedFilterButton: `button div.text-sm:text-is('ultra-soft')`,
  extraSoftButtonAppliedFilterButton: `button div.text-sm:text-is('Extra Soft')`,
  compactButtonAppliedFilterButton: `button div.text-sm:text-is('Compact')`,
  ultraCompactButtonAppliedFilterButton: `button div.text-sm:text-is('Ultra Compact')`,
  kidsAndTweensButtonAppliedFilterButton: `button div.text-sm:text-is('Kids & Tweens')`,
  toothBrushesText: `nav li a:text-is('Toothbrushes')`,
  softButtonText: `div.navigation-submenu-container a p:text-is('Soft')`,
  extraSoftButtonText: `div.navigation-submenu-container a p:text-is('Extra soft')`,
  ultraSoftButtonText: `div.navigation-submenu-container a p:text-is('Ultra Soft')`,
  compactButtonText: `div.navigation-submenu-container a p:text-is('Compact')`,
  ultraCompactButtonText: `div.navigation-submenu-container a p:text-is('Ultra Compact')`,
  kidsAndTweensButtonText: `div.navigation-submenu-container a p:text-is('Kids & Tweens')`,
  fluoridesText: `nav li a:text-is('Fluorides')`,
  colgatePreviDentSeriesButtonText: `div.navigation-submenu-container a p:text-is('Colgate® PreviDent® Series')`,
  colgateGelKamButtonText: `div.navigation-submenu-container a p:text-is('Colgate® Gel-Kam®')`,
  toothpasteButtonText: `div.navigation-submenu-container a p:text-is('Toothpaste')`,
  gelButtonText: `div.navigation-submenu-container a p:text-is('Gel')`,
  varnishButtonText: `div.navigation-submenu-container a p:text-is('Varnish')`,
  colgatePrevidentSeriesButtonAppliedFilterButton: `button div.text-sm:text-is('Colgate® Prevident Series')`,
  colgateGelKamButtonAppliedFilterButton: `button div.text-sm:text-is('Colgate® Gel-Kam')`,
  toothpasteButtonAppliedFilterButton: `button div.text-sm:text-is('Toothpaste')`,
  gelButtonAppliedFilterButton: `button div.text-sm:text-is('Gel')`,
  varnishButtonAppliedFilterButton: `button div.text-sm:text-is('Varnish')`,
  moreMenuText: `//a[@title='See more categories']`,
  mouthwashButtonText: `//span[@data-testid="category-option" and text()='Mouthwash']`,
  toothpastButtonText: `//span[@data-testid="category-option" and text()='Toothpaste']`,
  floosButtonText: `//span[@data-testid="category-option" and text()='Floss']`,
  professionalsText: `//a[@title='Professional']`,
  shopText: `//a[@title='Shop']`,
  oralHealthNetworkText: `//a[@title='Shop']`,
  welcomeTextText: ` //h1[contains(text(), 'Welcome to Colgate')]`,
  welcomeSubTextText: ` //p[contains(text(), 'Everything you need to quickly order and manage oral care essentials for your office')]`,
  joinButtonText: `//button[text()='Join']`,
  profileIcon: "//button[@aria-label='my account']//span[contains(@class,'user-icon navigation')]",
  joinButtonHeader: `//div[@id='user-account']//a[text()='Join']`,
  quickAndEasyOrderingText: `(//*[text()='Quick & Easy Ordering'])[1]`,
  saveMoreWithColgateText: `(//*[contains(text(), 'Save More with Colgate')])[1]`,
  trustedByDentalText: `(//*[text()='Trusted by Dental Professionals Worldwide'])[1]`,
  newToStoreText: `//h3[text()='New To Store']`,
  newToStoreSubTextText: `//p[text()='Receive bigger savings for larger orders with our top-selling products']`,
  newToStoreSignInText: ` //p[contains(text(), 'Receive bigger')]/following-sibling::button[text()='Sign in to view prices']`,
  welcomeTextHeadingAfterLoginText: '//div[@class="hero-banner"]//h1[text()="Save with Colgate"]',
  productCharcoalToothbrushText: `//p[@title='Colgate® 360® Charcoal Toothbrush']`,
  shopByConditionText: `//h3[text()='Shop By Patient Condition']`,
  shopByConditionPreviousButtonText: `//h3[text()='Shop By Patient Condition']//../following-sibling::div/div/div[@class='swiper-button-prev']`,
  shopByConditionNextButtonText: `//h3[text()='Shop By Patient Condition']//../following-sibling::div/div/div[@class='swiper-button-next']`,
  betterValueAndMoreText: `//div[text()='BETTER VALUE & MORE CONVENIENCE']`,
  newWayToShopText: `//h3[contains(text(),'Introducing a new way to shop with Colgate')]`,
  newWayToShopSubTextText: `//p[contains(text(),'Maximize time and minimize effort with the new Colgate')]`,
  ourInnovativeProductText: `//h2[text()='Our Innovative Products']`,
  innovativeProductSubTextText: `//p[text()='Explore the latest technology in oral health to empower your practice.']`,
  innovativeProductSignInText: `//p[contains(text(), 'Explore the latest technology')]/following-sibling::button[text()='Sign in to view prices']`,
  shopByFluoridesText: `//h2[text()='Shop By Fluorides']`,
  shopByFluorideSubTextText: `//p[text()='Buy more, save more.']`,
  shopByFlorideSignInText: `//p[text()='Buy more, save more.']/following-sibling::button`,
  profileJoinButtonText: `(//a[text()='Join'])[2]`,
  profileButtonText: `//button[@aria-label='my account' and @aria-controls='user-account']`,
  cartButtonText: "//button[@aria-controls='login-flyout-1']",
  cartJoinButtonText: `(//a[text()='Join'])[3]`,
  profileSignInButtonText: `//div[@id='user-account']//div//div//button[text()="Sign In"]`,
  cartSignInButtonText: `//div[@id="login-flyout-1"]//button[text()='Sign In']`,
  profileText: `//div[contains(@class, 'headeraction-buttons')]//button[contains(@aria-label,'my account')]`,
  cartText: `//button[@aria-label='cart']`,
  cartToCheckOutButtonText: `//button[text()='Checkout']`,
  productAddToCartButton: `(//*[contains(@title, 'Colgate® Optic White® Professional Take-Home Whitening (6% Hydrogen Peroxide)')])[2]//..//..//../following-sibling::div//button`,
  signInButtonText: '//span[@class="flex gap-[2rem] flex-wrap"] //button[text()="Sign In"]',
  newToStoreSignInToViewPricesButton: `(//button[text()='Sign in to view prices'])[1]`,
  innovativeProductsSignInToViewPricesButton: `//h2[text()='Our Innovative Products']/ancestor::div[contains(@class,'flex flex-col')]//button[text()='Sign in to view prices']`,
  shopByFluoridesSignInToViewPricesButton: '//h2[text()="Shop By Fluorides"]/ancestor::div[contains(@class,"flex flex-col")]//button[text()="Sign in to view prices"]',
  moreToExploreSignInToViewPricesButton: '//h2[text()="More To Explore"]/ancestor::div[contains(@class,"flex flex-col")]//button[text()="Sign in to view prices"]',
  shopByWhiteningSignInToViewPricesButton: '//h2[text()="Shop By Whitening"]/ancestor::div[contains(@class,"flex flex-col")]//button[text()="Sign in to view prices"]',
  shopByPatientConditionsMenuText: '//a[contains(text(), "Shop By Patient Condition") and contains(@class, "menu-title")]',
  sensitivityText: '//span[@data-testid="category-option" and contains(text(), "Sensitivity")]',
  orthoText: '//span[@data-testid="category-option" and contains(text(), "Ortho")]',
  gingivitisPerioText: '//span[@data-testid="category-option" and contains(text(), "Gingivitis / Perio")]',
  cariesText: '//span[@data-testid="category-option" and contains(text(), "Caries")]',
  whiteningText: '//a[contains(text(), "Whitening") and contains(@class, "menu-title")]',
  erosionText: '//span[@data-testid="category-option" and contains(text(), "Erosion")]',
  dryMouthText: '//span[@data-testid="category-option" and contains(text(), "Dry Mouth")]',
  colgatePreviDentSeriesText: '//p[text()="Colgate® PreviDent® Series"]',
  colgateGelkamText: '//p[text()="Colgate® Gel-Kam®"]',
  viewAllFluoridesText: '//a[@title="View All Fluoride Therapy By Product"]',
  toothpasteText: '//p[text()="Toothpaste"]',
  gelText: '//p[text()="Gel"]',
  varnishText: '//p[text()="Varnish"]',
  viewAllFluoridesByTherapyText: '//a[@title="View All Fluoride Therapy By Formula"]',
  colgatePerioGuardRinsesText: '//p[text()="Colgate® PerioGard® Rinse"]',
  colgatePeroxylRinsesText: '//p[text()="Colgate® Peroxyl® Rinse"]',
  colgatePhosFlurRinseText: '//p[text()="Colgate® Phos-Flur® Rinse"]',
  viewAllOralRinsesText: '//a[@title="View All Oral Rinses By Product"]',
  takeHomeWhiteningText: '//p[text()="Take-Home Whitening kit"]',
  whiteningRefillPenText: '//p[text()="Whitening Refill Pen"]',
  viewAllWhiteningText: '//a[@title="View All Whitening Take Home"]',
  mouthwashSubmenuText: '//span[normalize-space()="Mouthwash"]',
  toothpasteSubmenuText: '//span[normalize-space()="Toothpaste"]',
  flossSubmenuText: '//span[normalize-space()="Floss"]',
  shopNowShopWithColgateButton: '//div[@class="pt-10 lg:pt-4 pb-12 lg:pb-32 promotion-banner-anchor-wrapper"]//a[@title="Shop now"]',
  shopNowImageOneButton: '//img[@alt="Rectangle 600"]/ancestor::div[contains(@class, "promotionbanner")]//a[@title="Shop Now"]',
  shopNowImageTwoButton: '//img[@alt="Spotlight Banner Dark Red"]/ancestor::div[contains(@class, "promotionbanner")]//a[@title="Shop Now"]',
  shopNowImageThreeButton: '//div[@class="max-w-[var(--promotion-banner-text-width-fullbleed)] lg:py-5 py-14 promobanner relative min-h-[20rem] z-10"]//a[@title="Shop now"]',
  shopNowToothbrushesButton: '//div[contains(@class,"lg:grid lg:grid-cols-2 lg:col-span-2") and contains(.,"Select Colgate® Care")]//button',
  shopNowFluoridesButton: '(//div[contains(@class,"lg:grid lg:grid-cols-2 lg:col-span-2") and contains(.,"Colgate® PreviDent® 5000")]//button)[1]',
  shopNowOralRinsesButton: '(//div[contains(@class,"lg:grid lg:grid-cols-2 lg:col-span-2") and contains(.,"Colgate® PreviDent® 5000")]//button)[2]',
  shopNowWhiteningButton: '//div[contains(@class,"lg:grid lg:grid-cols-2 lg:col-span-2") and contains(.,"Colgate® Optic White® Professional")]//button',
  welcometextWelcomeToColgateText: '//div[@class="hero-banner"]//h1[text()="Welcome to Colgate"]',
  welcometextTwoRlogoText: '//div[@class="hero-banner"]//sup[text()="®"]',
  welcometextProfessionalText: '//div[@class="hero-banner"]//h1[text()=" Professional"]',
  quickAndEasyOrderingWelcomeToColgateText: '(//div[text()="Quick & Easy Ordering"])[2]',
  quickAndEasyOrderingFooterText: '(//div[text()="Quick & Easy Ordering"])[1]',
  saveMoreWelcomeToColgateText: 'text(//div[text()="Save More with Colgate"])[2]',
  saveMoreWelcomeToColgateFooterText: '(//div[text()="Save More with Colgate"])[1]',
  trustedByDentalProfessionalWelcomeToColgateText: '(//div[text()="Trusted by Dental Professionals Worldwide"])[2]',
  trustedByDentalProfessionalFooterText: '(//div[text()="Trusted by Dental Professionals Worldwide"])[1]',
  newToStoreHeadingText: '//h3[text()="New To Store"]',
  newToStoreSubHeadingText: '//p[text()="Receive bigger savings for larger orders with our top-selling products"]',
  shopByPatientConditionHeadingText: '//h3[text()="Shop By Patient Condition"]',
  enableCarouselShopByPatientConditionButton: '//div[contains(@class, "container overflow-hidden mb-12 patient-condition")] //div[@class="swiper-button-next"]',
  disableCarouselShopByPatientConditionButton: '//div[contains(@class, "container overflow-hidden mb-12 patient-condition")] //div[@class="swiper-button-prev swiper-button-disabled"]',
  carouselImgSensitivityButton: '//div[@class="swiper-wrapper"] //a[text()="Sensitivity"]',
  carouselImgOrthoButton: '//div[@class="swiper-wrapper"] //a[text()="Ortho"]',
  carouselImgGingivitisButton: '//div[@class="swiper-wrapper"] //a[text()="Gingivitis / Perio"]',
  carouselImgCariesButton: '//div[@class="swiper-wrapper"] //a[text()="Caries"]',
  carouselImgWhiteningButton: '//div[@class="swiper-wrapper"] //a[text()="Whitening"]',
  carouselImgErosionButton: '//div[@class="swiper-wrapper"] //a[text()="Erosion"]',
  carouselImgDryMouthButton: '//div[@class="swiper-wrapper"] //a[text()="Dry Mouth"]',
  ourInnovativeProductsHeadingText: '//h2[text()="Our Innovative Products"]',
  ourInnovativeProductssubHeadingText: '//p[text()="Explore the latest technology in oral health to empower your practice."]',
  shopByFluoridesHeadingText: '//h2[text()="Shop By Fluorides"]',
  shopByFluoridesSubHeadingText: '//p[text()="Buy more, save more."]',
  enableFluoridesCarouselsButton: '//div[contains(@class, " product-carouselhome-shop-by-fluoridesp2LFj home-shop-by-fluorides carousel-section")] //div[@class="swiper-button-next"]',
  disableFluoridesCarouselsButton: '//div[contains(@class, " product-carouselhome-shop-by-fluoridesp2LFj home-shop-by-fluorides carousel-section")] //div[@class="swiper-button-prev swiper-button-disabled"]',
  marketingBannerText: '//div[@class="marketing-banner-wrapper"]//h2',
  learnMoreLinkButton: '//div[@class="relative flex"]//a[text()="Learn More"]',
  moreToExploreHeadingText: '//h2[text()="More To Explore"]',
  moreToExploreSubHeadingText: '//p[text()="Shop some of our top-selling products."]',
  moreToExploreEnableButton: '//div[contains(@class, " product-carouselhome-more-to-exploredsFPt home-more-to-explore carousel-section")] //div[@class="swiper-button-next"]',
  moreToExploreDisableButton: '//div[contains(@class, "product-carouselhome-more-to-exploredsFPt home-more-to-explore carousel-section")] //div[@class="swiper-button-prev swiper-button-disabled"]',
  shopByWhiteningHeadingText: '//h2[text()="Shop By Whitening"]',
  shopByWhiteningSubHeadingText: '//p[text()="See our latest innovation in whitening."]',
  scrollBackToTopButton: '//button[@aria-label="Scroll back to top"]',
  allProductsFooterSectionLink: '//a[@title="All Products"]',
  toothBrushesFooterSectionLink: '//a[@title="Toothbrushes"]',
  fluoridesFooterSectionLink: '//a[@title="Fluorides"]',
  oralRinsesFooterSectionLink: '//a[@title="Oral Rinses"]',
  whiteningFooterSectionLink: '//a[@title="Whitening"]',
  toothPasteFooterSectionLink: '//a[@title="Toothpaste"]',
  flossFooterSectionLink: '//a[@title="Floss"]',
  faqsFooterSectionLink: '//a[@title="FAQ"]',
  shippingAndReturnsFooterSectionLink: '//a[@title="Shipping & Returns"]',
  termsOfUseFooterSectionLink: '//a[@title="Terms of Use"]',
  privacyPolicyFooterSectionLink: '//a[@title="Privacy Policy"]',
  cookieConsentToolFooterSectionLink: '//a[@title="Cookie Consent Tool"]',
  doNotSellMyPersonalInformationFooterSectionLink: '//a[@title="Do Not Sell My Personal Information"]',
  facebookIconFooterSectionLink: '//img[@alt="Facebook"]',
  instagramIconFooterSectionLink: '//img[@alt="Instagram"]',
  linkedInFooterSectionLink: '//img[@alt="LinkedIn"]',
  serviceHours1FooterSectionText: '(//p[@class="text-base font-light leading-7"])[1]',
  serviceHours2FooterSectionText: '(//p[@class="text-base font-light leading-7"])[2]',
  buyAgainHeadingText: '//h2[text()="Buy Again"]',
  buyAgainSubHeadingText: '//p[text()="Buy again from recent orders"]',
  practiceFavoritesHeadingText: '//h2[text()="Practice Favorites"]',
  practiceFavoritesSubHeadingText: '//p[text()="Shop the best selling products."]',
  ourInnovativeProductsAfterLoginHeadingText: '//h2[text()="Our Innovative Products"]',
  ourInnovativeProductsAfterLoginSubHeadingText: '//p[text()="Explore the latest technology in oral health to empower your practice."]',
  shopByManualToothbrushesHeadingText: '//h2[text()="Shop by Manual Toothbrushes"]',
  shopByManualToothbrushesSubHeadingText: '//p[text()="Explore more..."]',
  mostOrderedProductHeadingText: '//h2[text()="Most-Ordered Products"]',
  mostOrderedProductSubHeadingText: '//p[text()="Some of our top-selling products approved by dental experts to help you get started on products."]',
  addToCartButton: '//button[@aria-label="cart section"]',
  myAccountButton: '//button[@aria-label="my account" and contains(@class, "user-account-button")]',
  shopByPatientConditionSubMenuWrapperText: '//div[contains(@id, "navigation-submenu-wrapper-1")]',
  sensitivitySubMenuText: `div.navigation-submenu-container a span:text-is('Sensitivity')`,
  orthoSubMenuText: `div.navigation-submenu-container a span:text-is('Ortho')`,
  gingivitisOrPerioSubMenuText: `div.navigation-submenu-container a span:text-is('Gingivitis / Perio')`,
  cariesSubMenuText: `div.navigation-submenu-container a span:text-is('Caries')`,
  whiteningSubMenuText: 'div.navigation-submenu-container a span:text-is("Whitening")',
  erosionSubMenuText: `div.navigation-submenu-container a span:text-is('Erosion')`,
  dryMouthSubMenuText: `div.navigation-submenu-container a span:text-is('Dry Mouth')`,
  toothBrushesMenuLink: `nav li a:text-is('Toothbrushes')`,
  softSubMenuText: `div.navigation-submenu-container a p:text-is('Soft')`,
  extraSoftSubMenuText: `div.navigation-submenu-container a p:text-is('Extra soft')`,
  ultraSoftSubMenuText: `div.navigation-submenu-container a p:text-is('Ultra Soft')`,
  compactSubMenuText: `div.navigation-submenu-container a p:text-is('Compact')`,
  ultraCompactSubMenuText: `div.navigation-submenu-container a p:text-is('Ultra Compact')`,
  kidsAndTweensSubMenuText: `div.navigation-submenu-container a p:text-is('Kids & Tweens')`,
  fluoridesSubMenuWrapperText: '//div[contains(@id, "navigation-submenu-wrapper-3")]',
  colgatePreviDentSeriesButton: `div.navigation-submenu-container a p:text-is('Colgate® PreviDent® Series')`,
  colgateGelKamButton: `div.navigation-submenu-container a p:text-is('Colgate® Gel-Kam®')`,
  toothpasteButton: `div.navigation-submenu-container a p:text-is('Toothpaste')`,
  gelButton: `div.navigation-submenu-container a p:text-is('Gel')`,
  varnishButton: `div.navigation-submenu-container a p:text-is('Varnish')`,
  periogardButtonAppliedFilterButton: 'button div.text-sm:text-is("Colgate® Periogard Rinse")',
  peroxylButtonAppliedFilterButton: 'button div.text-sm:text-is("Colgate® Peroxyl® Rinse")',
  phosflurButtonAppliedFilterButton: 'button div.text-sm:text-is("Colgate® Phos-Flur ® Rinse")',
  whiteningSubMenuWrapperText: '//div[contains(@id, "navigation-submenu-wrapper-7")]',
  inOfficeWhiteningKitText: '//p[text()="In-Office Whitening Kit"]',
  takeHomeHeadingText: '//h1[contains(text(), "Take-Home Whitening")]',
  refillPenHeadingText: '//h1[contains(text(), "Refill Pen")]',
  inOfficeWhiteningHeadingText: '//h1[contains(text(), "In-Office Whitening")]',
  moreSubMenuWrapperText: '//div[contains(@id, "navigation-submenu-wrapper-8")]',
  mouthwashButtonAppliedFilterButton: 'button div.text-sm:text-is("Mouthwash")',
  flossButtonAppliedFilterButton: 'button div.text-sm:text-is("Floss")',
  accountIconButton: '//span[@class="user-icon navigationuser-iconq4Xpe"]',
  sensitiveSkinButton: `button[aria-label="Sensitive Skin"]`,
  cartIconButton: '//button[@aria-label="Open shopping cart"]',
  emptyCartButton: '//button[@aria-label="Clear Cart"]',
  shopByFluorideButton: `//button[contains(text(), "Fluoride")]`,
  moreItemModalText: '//div[contains(@class, "MuiDialog-root")]/div[contains(@class, "MuiDialogContent-root")]',
  textOverlayForSubMenuText: `//div[contains(@class, "overlay-overlay")]`,
  sensivityProductText: "//p[@title='Colgate® PreviDent® Varnish (5% Sodium Fluoride)']",
  sensivityProductAddToCartButton: "//div[contains(@aria-label, 'Colgate® PreviDent® Varnish')]//button[@aria-label='Add to Cart Mint']",
  itemAddedToCartText: "//div[text()='Item Added To Cart']",
  itemAddedToCartCloseButton: "//button[@aria-label='close']",
  practiceFavoritesProductAddToCartButton: "//div[@aria-label='<h2>Practice Favorites</h2>']//button[@aria-label='Add to Cart Colgate® Optic White® Professional Take-Home Whitening Kit - 6% Hydrogen Peroxide']",
  itemAddedSuccessfullyToCartText: "//div[text()='Item Successfully Added to Cart']",
  toothbrushMenuLink: '//a[contains(text(), "Toothbrushes") and contains(@class, "menu-title")]',
  softSubMenuLink: 'li.navigation-filter-options a[title="Soft"]',
  toothbrushSubmenuWrapper: '//div[contains(@id, "navigation-submenu-wrapper-2")]',
  colgateBadgeImage: '//img[@alt="Colgate Palmolive"]',
  oralRinsesMenuLink: '//a[contains(text(), "Oral Rinses") and contains(@class, "menu-title")]',
  oralRinsesSubMenuWrapper: '//div[contains(@id, "navigation-submenu-wrapper-6")]',
  colgatePerioGardRinseSubMenuLink: '//a[@href="/products?category=Oral%20Rinses&category-2=colgate--periogard-rinse"]',
  shopByPatientConditionLink: `nav li a:text-is('Shop By Patient Condition')`,
  orthoAppliedFilterButton: `button div.text-sm:text-is('Ortho')`,
  gingivitisOrPerioAppliedFilterButton: `button div.text-sm:text-is('Gingivitis/Perio')`,
  cariesAppliedFilterButton: `button div.text-sm:text-is('Caries Adult')`,
  whiteningAppliedFilterButton: `button div.text-sm:text-is('Whitening')`,
  erosionAppliedFilterButton: `button div.text-sm:text-is('Erosion')`,
  dryMouthAppliedFilterButton: `button div.text-sm:text-is('Dry Mouth')`,
  softAppliedFilterButton: `button div.text-sm:text-is('Soft')`,
  ultraSoftAppliedFilterButton: `button div.text-sm:text-is('Ultra Soft')`,
  extraSoftAppliedFilterButton: `button div.text-sm:text-is('Extra Soft')`,
  compactAppliedFilterButton: `button div.text-sm:text-is('Compact')`,
  ultraCompactAppliedFilterButton: `button div.text-sm:text-is('Ultra Compact')`,
  kidsAndTweensAppliedFilterButton: `button div.text-sm:text-is('Kids & Tweens')`,
  toothbrushesLink: `nav li a:text-is('Toothbrushes')`,
  softButton: `div.navigation-submenu-container a p:text-is('Soft')`,
  extraSoftButton: `div.navigation-submenu-container a p:text-is('Extra soft')`,
  ultraSoftButton: `div.navigation-submenu-container a p:text-is('Ultra Soft')`,
  compactButton: `div.navigation-submenu-container a p:text-is('Compact')`,
  ultraCompactButton: `div.navigation-submenu-container a p:text-is('Ultra Compact')`,
  kidsAndTweensButton: `div.navigation-submenu-container a p:text-is('Kids & Tweens')`,
  fluoridesLink: `nav li a:text-is('Fluorides')`,
  colgatePrevidentSeriesAppliedFilterButton: `button div.text-sm:text-is('Colgate® Prevident Series')`,
  colgateGelKamAppliedFilterButton: `button div.text-sm:text-is('Colgate® Gel-Kam')`,
  toothpasteAppliedFilterButton: `button div.text-sm:text-is('Toothpaste')`,
  gelAppliedFilterButton: `button div.text-sm:text-is('Gel')`,
  varnishAppliedFilterButton: `button div.text-sm:text-is('Varnish')`,
  moreMenuLink: `//a[@title='See more categories']`,
  mouthwashButton: `//span[@data-testid="category-option" and text()='Mouthwash']`,
  toothpasteCategoryButton: `//span[@data-testid="category-option" and text()='Toothpaste']`,
  flossButton: `//span[@data-testid="category-option" and text()='Floss']`,
  professionalsLink: `//a[@title='Professional']`,
  shopLink: `//a[@title='Shop']`,
  oralHealthNetworkLink: `//a[@title='Shop']`,
  welcomeText: `//h1[contains(text(), 'Welcome to Colgate')]`,
  welcomeSubText: `//p[contains(text(), 'Everything you need to quickly order and manage oral care essentials for your office')]`,
  joinButton: `//button[text()='Join']`,
  signInButton: `//button[text()='Join']/following-sibling::button`,
  newToStoreHeading: `//h3[text()='New To Store']`,
  newToStoreSubText: `//p[text()='Receive bigger savings for larger orders with our top-selling products']`,
  newToStoreSignInButton: `//p[contains(text(), 'Receive bigger')]/following-sibling::button[text()='Sign in to view prices']`,
  itemAddedSuccessfullyToCart: "//div[text()='Item Successfully Added to Cart']",
  welcomeTextAfterLogin: '//div[@class="hero-banner"]//h1[text()="Save with Colgate"]',
  fAQ: "//div[normalize-space()='FAQs']",
  fAQsFooterSection: '//a[@title="FAQ"]',
  shippingAndReturnsFooterSection: '//a[@title="Shipping & Returns"]',
  shippingAndReturn: "//div[normalize-space()='Shipping & Returns']",
  facebookIcon: "(//img[@alt='Facebook'])[1]",
  instagramIcon: "(//img[@alt='Instagram'])[1]",
  linkdinIcon: "(//img[@alt='LinkedIn'])[1]",
  needHelp: "(//p[normalize-space()='Need Help?'])[1]",
  callNo: "(//a[normalize-space()='Call:1-800-226-5428'])[1]",
  serviceEmail: "(//a[normalize-space()='or email: Service@colgatepro.com'])[1]",
  serviceHoursOneFootersection: '(//p[@class="text-base font-light leading-7"])[1]',
  serviceHoursTwoFootersection: '(//p[@class="text-base font-light leading-7"])[2]',
  scrollBacktoTopbutton: '//button[@aria-label="Scroll back to top"]',
  verifyScrollBackToTop: "(//h1[@id='heroheading'])[1]",
  customerService: "//p[text()='Customer Services']",
  buyAgain: "//button[text()='Buy Again']",
  practiceFavoriteText: `//h2[text()='Practice Favorites']`,
  moreToExploreText: `//h2[text()='More To Explore']`,
  shopByWhitening: `//h2[text()='Shop By Whitening']`,
  pdpCharcoalText: `//h1[text()='Colgate® 360® Charcoal Toothbrush']`,
  allShopNowButton: `//a[@title='Shop now' and @href="/products"]`,
  allProductText: `//div[text()='All Products']`,
  learnMoreLink: `//a[text()='Learn More']`,
  faqsText: `//div[text()='FAQs']`,
  selectProductButton: `(//*[contains(@title,'Colgate® 360® Deep Clean Ultra-Compact Head Toothbrush')])//..//..//..//following-sibling::div//a[text()='Select Product']`,
  productNameText: `(//*[contains(@title,'Colgate® 360® Deep Clean Ultra-Compact Head Toothbrush')])`,
  productPriceText: `(//*[contains(@title,'Colgate® 360® Deep Clean Ultra-Compact Head Toothbrush')])`,
  iteamAddedToCartText: `//div[text()='Item Added To Cart']`,
  footerAllProductsLink: "//a[text()='All Products']",
  footerToothbrushesLink: "(//a[text()='Toothbrushes'])[2]",
  footerFluoridesLink: "(//a[text()='Fluorides'])[2]",
  footerOralRinsesLink: "(//a[text()='Oral Rinses'])[2]",
  footerWhiteningLink: "(//a[text()='Whitening'])[2]",
  footerMouthwashLink: "//a[text()='Mouthwash']",
  footerFlossLink: "//a[text()='Floss']",
  footerToothpasteLink: "//a[text()='Toothpaste']",
  footerCustomerServiceText: "//p[text()='Customer Services']",
  footerFaqLink: "//a[text()='FAQ']",
  footerShippingReturnLink: "//a[text()='Shipping & Returns']",
  footerUsefulLinksText: "//p[text()='Useful Links']",
  footerTermsOfUseLink: "//a[text()='Terms of Use']",
  footerPrivacyPolicyLink: "//a[text()='Privacy Policy']",
  footerCookiesConsentLink: "//a[text()='Cookie Consent Tool']",
  footerDoNotSellMyPersonalInformationLink: "//a[text()='Do Not Sell My Personal Information']",
  footerFacebookLink: "//a[@title='Facebook']",
  footerInstagramLink: "//a[@title='Instagram']",
  footerLinkedInLink: "//a[@title='LinkedIn']",
  footerNeedHelpText: "//p[text()='Need Help?']",
  footerCallUsText: "//a[contains(text(), 'Call:')]",
  footerEmailUsText: "//a[contains(text(), 'or email:')]",
  footerMonThuText: "//p[contains(text(), 'Mon - Thu:')]",
  footerFriText: "//p[contains(text(), 'Fri:')]",
  footerCopyrightText: "//p[text()='© 2024 Colgate-Palmolive Company. All Rights Reserved.']",
  toothbrushPageHeading: "//div[text()='Toothbrush' and contains(@class, 'heading')]",
  shopProductFooterSection:"//p[text()='Shop Products']",
  shopNowAfterLogin: '//div[@class="pt-10 lg:pt-4 pb-12 lg:pb-32 promotion-banner-anchor-wrapper"]//a[@title="Shop now"]',
  addToCartButtonOralRines:`//button[@aria-label='Add to Cart Colgate® Peroxyl® Antiseptic Rinse Sachets']`,
  addToCartWhitening:`button[aria-label='Add to Cart Colgate® Optic White® Professional Take-Home Whitening (6% Hydrogen Peroxide) Colgate® Optic White® Professional Take-Home Whitening Kit - 6% Hydrogen Peroxide']`,
  homePageOrdresButton: "(//ul[contains(@class,'global-account-list')]//child::a[text()='Orders'])[2]",
  homePageBuyAgainProductName: "(//button[text()='Buy Again']/ancestor::div[contains(@class,'product-card')]//child::p)[1]",
  homePageBuyAgainButton: "(//button[text()='Buy Again'])[1]",
  homePageItemAddedToCart: "//div[text()='Item Added To Cart']",
  shopNowImage1Button: '//img[@alt="Rectangle 600"]/ancestor::div[contains(@class, "promotion_banner")]//a[@title="Shop Now"]',
  shopNowImage2Button: '//img[@alt="Spotlight Banner Dark Red"]/ancestor::div[contains(@class, "promotion_banner")]//a[@title="Shop Now"]',
  shopNowImage3Button: '//div[@class="max-w-[var(--promotion-banner-text-width-fullbleed)] lg:py-5 py-14 promo_banner relative min-h-[20rem] z-10"]//a[@title="Shop now"]',
  welcometext2RlogoText: '//div[@class="hero-banner"]//sup[text()="®"]',
  colgateProductText:`(//p[@title='Colgate® PreviDent® 5000 ppm Booster Plus (1.1% Sodium Fluoride)'])[1]`,
  colgateProductVariant:`(//div[contains(@class,'product_card')] //span[@title='Fruitastic'])[1]`,
  colgateProductAddToCartButton:`div.product_card:has-text('Colgate® PreviDent® 5000 ppm Booster Plus (1.1% Sodium Fluoride)') button >> nth=0`
  }  