export const HomeLocators = {
  //header Locators

  homePageFlex: "//ul[@class='flex']",
  homePageHeader: "//div[@class='flex items-center justify-center lg:justify-end text-sm gap-3']",
  pcaSkinLogo: "//img[@alt='logo']",
  menuTitleShop: "//a[contains(text(), 'shop')]",
  menuTitleacademy: "//a[contains(text(), 'academy')]",
  menuTitleEvents: "//a[contains(text(), 'Events')]",
  menuTitleAbout: "//a[contains(text(), 'About')]",
  menuTitleBusinessTools: "//a[contains(text(), 'Business Tools')]",
  menuTitleMicrosites: "//a[contains(text(), 'Microsites')]",
  menuTitleStudent: "//a[contains(text(), 'Student')]",
  searchProductsAndCourses: "//button[@aria-label='Search Products and Courses']",
  userIcon: "//span[@class='user-icon navigation_user-icon__qKUdK flex']",
  logInUserAccount: "//div[@id='user-account']//button[normalize-space()='Log In']",
  createAccount: "//div[contains(@class,'flyout-container')]//a[contains(@class,'text-primary-400') and text()='Create Account']",
  accountText: "//h2[text()='If you have a professional account, please login. If you would like to establish a professional account please click Create Account.']",
  shoppingCartIcon: "//button[@aria-label='cart icon']",
  userCreateAccountBtn: "//div[@id='user-account']//a[normalize-space()='Create Account']",

  // Center page element locators 

  welcomeSkinProfessionalSite: "//h1[text()='Welcome to the PCA SKIN Professional Site']",
  alreadyOnlineAccount: "//p[text()='If you have an online account, please login. Need an online account?']",
  registerNow: "//a[text()='Register Now']",
  alreadyRegistered: "//h1[@id='greeting-login-container_content_caption']",
  inputEmail: "//input[@aria-label='Email']",
  inputPassword: "//div[@class='gigya-composite-control gigya-composite-control-password']//input[@placeholder='Password *']",
  forgotPassword: "//a[@title='Forgot your password?']",
  loginBtnUserAccount: "//div[@id='user-account']/div/div/button[text()='Log In']",
  loginButton: "//div[@class='gigya-layout-cell']//input[@value='Log in']",
  homeSliderImage: "//img[contains(@src, '2c22f386-db3f-44b7-bca4-47062212ea72.jpg')]",
  homeSliderTextHeader: "//div[text()='A new way to brighten has emerged']",
  homeSliderText: "//div[text()='Introducing our first brightening moisturizer for deeper hydration and luminous glow.']",
  shopNow: "//a[contains(@aria-label, 'shop Now')]",
  swiperPagination: "//div[contains(@class, 'swiper-pagination')]",
  learnMoreNewBrightEvenPeel: "//a[contains(@aria-label,'learn more : NEW Bright and Even Peel')]",
  learnMoreCelebrateNationalPeelDay: "//a[contains(@aria-label,'learn more : Celebrate National Peel Day')]",
  swiperButtonNext: "div.hero-banner div.swiper-button-next",
  swiperButtonPrevious: "div.hero-banner div.swiper-button-prev",
  registerTreatmentTuesday: "//h2[@id='marketingHeading-Register Treatment Tuesday']",
  bannerDescription: "//p[@class='text-base font-light leading-6 banner-description']",
  marketingImage1: "//div[@class='marketing-banner-wrapper'] //img[@alt='Marketing Image 1']",
  marketingImage2: "//div[@class='marketing-banner-wrapper'] //img[@alt='Marketing Image 2']",
  learnMoreMarketingHeadingRegisterTreatmentTuesday: "//a[@aria-labelledby='marketingHeading-Register Treatment Tuesday']",
  betterValueAndMoreConvenience: "//div[@class='text-tertiary-400 font-bold text-sm tracking-[0.1rem] leading-16 short-title']",
  trustTheExperts: "//div[@class='py-3 text-xl font-bold tracking-normal text-primary-400 leading-28 lg:text-2xl promotion-banner-title']",
  promotionBannerDesc: "//div[contains(@class, 'promotion-banner-desc')]",
  orderManagementImg: "//picture[@class='lazyload-true is-loaded']//img[@alt='B2 B Site Order Managementt Icon 25x25']",
  orderManagement: "//p[text()='Order Management']",
  orderManagementText: "//div[contains(@class,'individual_benefits py-3')]//div[contains(@class,'font-light leading-6 text-tertiary-400 px-9 lg:px-0 benefits-description')][contains(text(),'Effortlessly handle orders and invoices in your ac')]",
  academyImg: "//img[@src='//img[@alt='B2 B Site academy Icon 25x25']']",
  academy: "//p[text()='academy']",
  academyText: "//div[contains(text(), 'Get access to the entire education library')]",
  loyaltyImg: "//img[@alt='B2 B Site loyalty Icon 25x25 (1)']",
  loyalty: "//p[text()='loyalty']",
  loyalty_Text_: "//div[contains(@class,'individual_benefits py-3')]//div[contains(@class,'font-light leading-6 text-tertiary-400 px-9 lg:px-0 benefits-description')][contains(text(),'Sign up to access exclusive perks, rewards, and sp')]",
  subscriptonsImg: "//picture[contains(@class,'lazyload-true is-loaded')]//img[contains(@alt,'B2 B Site Subscribe Icon 25x25')]",
  subscriptions: "//p[text()='subscriptions']",
  subscriptionsText: "//div[contains(@class,'individual_benefits py-3')]//div[contains(@class,'font-light leading-6 text-tertiary-400 px-9 lg:px-0 benefits-description')][contains(text(),'Keep your shelves stocked by auto-ordering all of ')]",
  pcaSKINProfessionalImageSrc: "//img[@alt='PCA SKIN Professional Peel Certification 2.0']",
  pcaSkinProfessionalHeading: "//h2[@id='marketingHeading-PCA SKIN Professional Peel Certification']",
  pcaSkinProfessionalText: "//p[contains(text(),'Complete this course as a certified PCA SKIN Profe')]",
  pcaSkinProfessionalLearnMoreButton: "//a[@aria-labelledby='marketingHeading-PCA SKIN Professional Peel Certification']",
  bestSellers: "//h2[normalize-space()='Best Sellers']",
  highlyRecommendedProdcuts: "//p[contains(text(),'A selection of our highly recommended products, en')]",
  loginInToViewPricesButton: "//button[normalize-space()='Log in to view prices']",
  bestSellersSwiperPreviousButton: "//div[@class='swiper-button-prev']",
  bestSellersSwiperNextButton: "//div[@class='swiper-button-next']",
  bestSellersProductImage: "//div[contains(@class,'swiper-slide swiper-slide-active')]//img[contains(@class,'object-contain product-card-picture-wrapper')]",
  productRatings: "//p[text()='C&E Hand Renewal']//parent::a//parent::div//preceding-sibling::div//div[@data-bv-show='inline_rating']//a]",
  acneCream: "//div[@class='swiper-slide swiper-slide-active']//div[@aria-label='Acne Cream false false']//div[@class='product-card-content product-card-content-wrapper']//div//p[@title='Acne Cream'][normalize-space()='Acne Cream']",
  cAndEHandRenewal: "//div[@class='swiper-slide swiper-slide-next']//div[@aria-label='C&E Hand Renewal false false']//div[@class='product-card-content product-card-content-wrapper']//div//p[@title='C&E Hand Renewal'][normalize-space()='C&E Hand Renewal']",
  cAndEAdvanced: "//div[@class='swiper-slide']//div[@aria-label='C&E Advanced false false']//div[@class='product-card-content product-card-content-wrapper']//div//p[@title='C&E Advanced'][normalize-space()='C&E Advanced']",
  noPeelPeel: "//div[@class='swiper-slide']//div[@aria-label='NoPeel Peel false false']//div[@class='product-card-content product-card-content-wrapper']//div//p[@title='NoPeel Peel'][normalize-space()='NoPeel Peel']",
  logInToOrderButton: "//div[@class='swiper-slide swiper-slide-active']//button[@aria-label='Log In to Order Acne Cream'][normalize-space()='Log In to Order']",
  loginForm: "//div[@id='login-container']//div[@class='gigya-layout-cell responsive with-site-login']",
  emailEmptyErrorMessage: "//input[@id='gigya-textbox-loginID']",
  resetMyPassword: "//input[@value='Reset My Password']",


  //Footer Locators
  shop: "//div[@class='flex py-4 footer-title-wrapper']//p[text()='shop']",
  allProducts: "//a[@title='All Products']",
  dailyCare: "//a[@title='Daily Care']",
  byTreatment: "//a[@title='By Treatment']",
  bySkinType: "//a[@title='By Skin Type']",
  bySkinConcern: "//a[@title='By Skin Concern']",
  learn: "//div[@class='flex py-4 footer-title-wrapper']//p[text()='learn']",
  courses: "//a[@title='Courses']",
  professionalPeels: "//a[@title='Professional Peels']",
  skinConcerns: "//a[@title='Skin Concerns']",
  skinTypes: "//a[@title='Skin Types']",
  skinIntelligence: "//a[@title='Skin Intelligence']",
  about: "//div[@class='flex py-4 footer-title-wrapper']//p[text()='About']",
  ourStory: "//a[@title='Our Story']",
  ourPeelLegacy: "//a[@title='Our Peel Legacy']",
  careers: "//a[@title='Careers']",
  customerService: "//div[@class='flex py-4 footer-title-wrapper']//p[text()='Customer Service']",
  contactUs: "//a[@title='Contact Us']",
  FAQ: "//a[@title='FAQ']",
  shipping: "//a[@title='Shipping']",
  returns: "//a[@title='Returns']",
  PCA_SKIN_International: "//a[@title='PCA SKIN International']",
  privacyPolicy: "//a[@title='Privacy Policy']",
  termsAndConditions: "//a[@title='Terms & Conditions']",
  doNotSellMyPersonalInformation: "//a[@title='Do Not Sell My Personal Information ']",
  productExcellence: "//a[@title='Product Excellence']",
  copyRight2024CPSkinHealthGroupInc: "//p[@class='text-sm font-light lg:text-base font-white']",
  scrollButton: "//body/div[@id='__next']/div/div/div[@data-testid='scroll-button']/button[1]",
  crouselLocator: "(//div[@data-testid='hero-content'])[1]",
  contentBanner2ColumnType: "//*[@id='marketing-banner-pca-en-us-content-banner']",
  promotionBanner: "//div[@data-testid='promotionBanner']",
  alreadyRegisterdEmailErrorMessage: "//span[@data-bound-to='loginID' and contains(@class,'gigya-error-msg-active')]",
  alreadyRegisterdPasswordErrorMessage: "//span[@data-bound-to='password' and contains(@class,'gigya-error-msg-active')]",
  alreadyRegisterdInvalidEmailPasswordMessage: "//div[@data-bound-to='gigya-login-form' and contains(@class,'gigya-error-msg-active')]",
  returnToLoginButton: "//div[@class='gigya-layout-cell']//a[@title='Return to Log In']",
  loginPopUp: "//div[@id='login-container']",
  learnMoreButton: "//a[@title='Learn More']",
  benifitlistVisible: "//div[contains(@class, 'hidden') and contains(@class, 'lg:grid') and contains(@class, 'benefit-lists')]",
  PCASKINtakesVisible: "//div[@class='px-4 lg:px-0 text-base promotion-banner-desc leading-6 text-tertiary-400']",
  trustExpertVisible: "//div[contains(@class, 'promotion-banner-title')]",
  betterValueVisible: "//div[contains(@class, 'short-title')]",


  heroBanner: `//div[@class="hero-banner" or @class="hero-banner-dark"]`,
  ordersSection: `//div[contains(@class, 'heading') and contains(text(), 'Orders')]/following-sibling::a[contains(@class, 'link')]`,
  marketingContentBanner: `//div[contains(@class,'marketing-banner-container content-banner')]`,
  orderAgainCarousel: `//h2[text()="Order Again"]/ancestor::div[contains(@class,'more-to-explore-carousel')]`,
  courseBanner: `//div[@aria-labelledby="marketing-banner-pca-en-us-course-banner"]`,
  bestSellerCarousel: `//h2[text()="Best Sellers"]/ancestor::div[contains(@class,'more-to-explore-carousel')]`,
  loyaltyTierLink: `//div[text()='Explore the Perks of PCA SKIN Rewards']/preceding-sibling::a`,
  customerSupportSection: `//div[contains(@class,'customer-service-wrapper')]`,
  orderAgainProductPrice: `//p[@title="Acne Gel with OmniSome®"]/ancestor::div[contains(@class,'product-card-content')]//div[contains(@class,'price-wrapper')]`, // Change the product title to locate other products
  orderAgainAddToCart: `//h2[text()='Order Again']/ancestor::div[contains(@class,'buy-again')]//p[text()='Acne Cream']/ancestor::div[contains(@class,'product-card-main-wrapper')]//button`,
  orderAgainSelectSize: `//h2[text()='Order Again']/ancestor::div[contains(@class,'buy-again')]//p[text()='Acne Gel with OmniSome®']/ancestor::div[contains(@class,'product-card-main-wrapper')]//a[text()='Select Size']`,
  maximumQtyReachedToast: `//div[@id="add-to-cart-api-error"]`,
  maximunQtyReachedCloseBtn: `//div[@id="add-to-cart-api-error"]//button`,

  bestSellerProductPrice: `div.relative.more-to-explore-carousel:has-text("Best Sellers") div.product-card-content.product-card-content-wrapper:has-text("Acne Cream") span.product-card-price-wrapper >> nth=1`, // Change the product title to locate other products
  bestSellerAddToCart: `div.product-card-main-wrapper:has-text('C&E Hand Renewal') button:has-text('Add to Cart') >> nth=1`,
  bestSellerSelectSize: `div.product-card-main-wrapper:has-text('C&E Hand Renewal') div.price-wrapper >> nth=1`,
  homePageImage: `//div[contains(@class,'swiper-slide swiper-slide-prev')]//img`,
  sliderHeading: `div.swiper-slide-active div.heading`,
  sliderDescription: `div.swiper-slide-active div.text-base.hero-desc-wrapper`,
  sliderDescription1: `div.swiper-slide div.hero-desc-wrapper:text-is("Introducing our first brightening moisturizer for deeper hydration and luminous glow.") >>nth=1`,
  sliderDescription2: `div.swiper-slide div.hero-desc-wrapper:text-is("A gentle and effective chemical peel with L-Mandelic and Lactic acids shown to increase visible skin brightness after just one peeling session.")`,
  sliderDescription3: `div.swiper-slide div.hero-desc-wrapper:text-is("Receive a complimentary face mask with purchase of a peel! To redeem, see instructions to the left") >>nth=1`,
  sliderCTALabel: `div.swiper-slide-active span.flex-wrap a`,
  sliderCTALabelShopNow: `div.swiper-slide span a >> nth=4`,
  sliderCTALabelLearnMore: `div.swiper-slide span a >> nth=2`,
  hydrabrightPageHeader: `div.product-info h1:text-is("HydraBright")`,
  brightAndEvenPeelPageHeader: `div.product-info h1:text-is("PCA SKIN® Bright & Even Peel")`,
  sliderTitle1: `div.swiper-slide div.heading:text-is("A new way to brighten has emerged") >>nth=1`,
  sliderTitle2: `div.swiper-slide div.heading:text-is("NEW Bright and Even Peel")`,
  sliderTitle3: `div.swiper-slide div.heading:text-is("Celebrate National Peel Day") >>nth=1`,
  noOrderText: `//td[contains(text(), 'No results found')]`,
  loyaltyRewardViewBenefits: `div.quick-link-tiles a.view-benefits`,
  loyaltyRewardTitlePage: `div.container h1:text-is("PCA Skin Rewards Program")`,
  customerSupportHeading: `div.customer-service-wrapper div.customer-support-content-wrapper h3`,
  customerSupportNumber: `div.customer-support-content-wrapper a p.customer-support-number`,
  availabilityDay: `div.customer-support-content-wrapper div.availability p.availability-day`,
  availabilityTime: `div.customer-support-content-wrapper div.availability p.availability-time`,

  // Content Banner
  brighteningLaunchPromo: `//h2[@id='marketingHeading-Brightening Launch Promo']`,
  contentBannerDescription1: `div.marketing-banner-wrapper p:text-is("Join us live to engage, learn, and shop with access to exclusive promotions")`,
  contentBannerDescription2: `div.marketing-banner-wrapper p:text-is("Buy 6 HydraBright and 1 Bright+Even Peel, get 6 bags. Buy 12 HydraBright and 1 Bright+Even Peel, get 12 bags + Brightening Mask. Code: BRIGHT24")`,
  learnMoreBrighteningLaunchPromo: `//a[@aria-labelledby='marketingHeading-Brightening Launch Promo']`,
  treatmentTuesday: `section.course-header h1:text-is("Treatment Tuesday")`,
  bestsellerDescription: `div.popular-products div.product-carousel-desc-wrapper p`,
  bestsellerBadge: `div.swiper-slide-active div.product-badge-wrapper span.best-seller.badge.tertiary.light`,
  bestsellerRating: `div.swiper-slide-active div.product-card-content div div a`,
  acneCreamTitle: `div.swiper-slide-active div p.title-wrapper`,
  productInfoPage: `div.product-info h1.product-name`,
  bestSellerAddToCartAcneCream: `(//div[contains(@class,'popular-products')]//p[text()='Acne Cream']/ancestor::div[contains(@class,'product-card-main-wrapper')]//button)[2]`,
  sliderCTALabelLearnMore2: `div.swiper-slide span a >> nth=3`,

}