export const NavigationHeaderLocators = {
    pcaSkinLogo: `//img[@alt="logo"]`,
    shopMenuList: `//li[contains(@class,'navigation-menu-list')]//a[text()='Shop']`,
    academyMenuList: `//li[contains(@class,'navigation-menu-list')]//a[text()='Academy']`,
    eventsMenuList: `//li[contains(@class,'navigation-menu-list')]//a[text()='Events']`,
    aboutMenuList: `//li[contains(@class,'navigation-menu-list')]//a[text()='About']`,
    businessToolsMenuList: `//li[contains(@class,'navigation-menu-list')]//a[text()='Business tools']`,
    micrositesMenuList: `//li[contains(@class,'navigation-menu-list')]//button[text()='Microsites']`,
    studentMenuList: `//li[contains(@class,'navigation-menu-list')]//button[text()='Student']`,

    dailyCareSubMenu: `//ul[contains(@class,'sub-menu')]//li//a[@title='Daily care']`,
    bestSellerDailyCareFilterOption: `//li[contains(@class,'navigation-filter-options')]//a[@title='Antioxidants']//p[text()='Best Seller']`,
    antioxidantsDailyCareFilterOption: `//li[contains(@class,'navigation-filter-options')]//p[text()='Antioxidants']`,
    broadSpectrumSPFDailyCareFilterOption: `//li[contains(@class,'navigation-filter-options')]//p[text()='Broad spectrum SPF']`,
    cleansersAndTonersDailyCareFilterOption: `//li[contains(@class,'navigation-filter-options')]//p[text()='Cleansers & toners']`,
    eyeNeckLipDailyCareFilterOption: `//li[contains(@class,'navigation-filter-options')]//p[text()='Eye, neck, lip']`,
    masksDailyCareFilterOption: `//li[contains(@class,'navigation-filter-options')]//p[text()='Masks']`,
    moisturizersDailyCareFilterOption: `//li[contains(@class,'navigation-filter-options')]//p[text()='Moisturizers']`,
    retinolsDailyCareFilterOption: `//li[contains(@class,'navigation-filter-options')]//p[text()='Retinols']`,
    serumsDailyCareFilterOption: `//li[contains(@class,'navigation-filter-options')]//p[text()='Serums']`,
    solutionSetsDailyCareFilterOption: `//li[contains(@class,'navigation-filter-options')]//p[text()='Solution sets']`,
    viewAllDailyCare: `//li[contains(@class,'navigation-filter-options')]//following::a[@aria-label="View All : Daily care"]`,

    professionalTreatmentsSubMenu: `//ul[contains(@class,'sub-menu')]//li//a[@title='Professional treatments']`,
    bestSellerProfTreatmentsFilterOption: `//li[contains(@class,'navigation-filter-options')]//a[@title='Peels']//p[text()='Best Seller']`,
    peelsProfTreatmentsFilterOption: `//li[contains(@class,'navigation-filter-options')]//p[text()='Peels']`,
    peelAlternativeProfTreatmentsFilterOption: `//li[contains(@class,'navigation-filter-options')]//p[text()='Peel alternative']`,
    retinoidTreatmentsProfTreatmentsFilterOption: `//li[contains(@class,'navigation-filter-options')]//p[text()='Retinoid treatments']`,
    therapeuticMasksProfTreatmentsFilterOption: `//li[contains(@class,'navigation-filter-options')]//p[text()='Therapeutic masks']`,
    treatmentEnhancementsProfTreatmentsFilterOption: `//li[contains(@class,'navigation-filter-options')]//p[text()='Treatment enhancements']`,
    backbarToolsProfTreatmentsFilterOption: `//li[contains(@class,'navigation-filter-options')]//p[text()='Backbar tools']`,
    viewAllProfTreatments: `//li[contains(@class,'navigation-filter-options')]//following::a[@aria-label="View All : Professional treatments"]`,

    bySkinTypeSubMenu: `//ul[contains(@class,'sub-menu')]//li//a[@title='By skin type']`,
    combinationBySkinTypeFilterOption: `//li[contains(@class,'navigation-filter-options')]//p//span[text()='Combination']`,
    dryBySkinTypeFilterOption: `//li[contains(@class,'navigation-filter-options')]//p//span[text()='Dry']`,
    normalBySkinTypeFilterOption: `//li[contains(@class,'navigation-filter-options')]//p//span[text()='Normal']`,
    oilyBySkinTypeFilterOption: `//li[contains(@class,'navigation-filter-options')]//p//span[text()='Oily']`,
    sensitiveBySkinTypeFilterOption: `//li[contains(@class,'navigation-filter-options')]//p//span[text()='Sensitive']`,
    viewAllBySkinType: `//li[contains(@class,'navigation-filter-options')]//following::a[@aria-label="View All : By skin type"]`,

    bySkinConcernSunMenu: `//ul[contains(@class,'sub-menu')]//li//a[@title='By skin concern']`,
    brighteningBySkinConcernFilterOption: `//li[contains(@class,'navigation-filter-options')]//p//span[text()='Brightening']`,
    acneBySkinConcernFilterOption: `div#navigation-submenu-wrapper-1 li span:text-is('Acne')`,
    agingBySkinConcernFilterOption: `div#navigation-submenu-wrapper-1 li span:text-is('Aging')`,
    discolorationBySkinConcernFilterOption: `//li[contains(@class,'navigation-filter-options')]//p//span[text()='Discoloration']`,
    preventativeBySkinConcernFilterOption: `//li[contains(@class,'navigation-filter-options')]//p//span[text()='Preventative']`,
    sensitiveSkinBySkinConcernFilterOption: `//li[contains(@class,'navigation-filter-options')]//p//span[text()='Sensitive Skin']`,
    viewAllBySkinConcern: `//li[contains(@class,'navigation-filter-options')]//following::a[@aria-label="View All : By skin concern"]`,

    navigationSearchBtn: `//div[contains(@class,'navigation-actions')]//button[@aria-label="Search Products and Courses"]`,
    navigationUserIcon: `//div[contains(@class,'navigation-actions')]//button[@aria-label="user icon"]`,
    navigationCartIcon: `//div[contains(@class,'navigation-actions')]//button[contains(@aria-label,"cart icon")]`,

    userIconInfoText: `div#user-account h2`,
    userIconLoginBtn: `div#user-account button`,
    userIconCreateAccount: `div#user-account a`,
    cartIconInfoText: `div#login-flyout-1 h2`,
    cartIconLoginBtn: `div#login-flyout-1 button`,
    cartIconCreateAccount: `div#login-flyout-1 a`,
    miniCartItemSection:`div.global-cart-items-section`,
    miniCartItemIncrease:`div.global-cart-items-section span.increase-icon`,

    afterLoginUserIconInfoText: `//div[@id="user-account"]//div[text()='Free drop-shipping for any order totalling $100 or more']`,
    afterLoginUserIconOverview: `div#user-account div.global-account-menu a[title='Overview']`,
    afterLoginUserIconOrders: `div#user-account div.global-account-menu a[title='Orders']`,
    afterLoginUserIconInvoices: `div#user-account div.global-account-menu a[title='Invoices']`,
    afterLoginUserIconSubscriptions: `div#user-account div.global-account-menu a[title='Subscriptions']`,
    afterLoginUserIconEducation: `div#user-account div.global-account-menu a[title='Education']`,
    afterLoginUserIconPersonalProfile: `div#user-account div.global-account-menu a[title='Personal Profile']`,
    afterLoginUseIconLogOut: `div#user-account div.global-account-menu button`,

    afterLoginCartIconInfoText: `//div[contains(@class,'global-cart-promotion-message')]`,
    afterLoginCartIconViewCartBtn: `//a[contains(@class,'global-cart-view-button')]`,
    afterLogincartIconCartEmptyView: `//div[contains(@class, 'global-cart-empty-view') and normalize-space(text())="There's nothing here yet."]`,
    afterLoginCartIconStartShoppingBtn: `//div[contains(@class, 'global-cart-empty-view')]/a[@title='Start Shopping']`,
    subTotalSection: `//div[contains(@class,'global-cart-subtotal')]`,

    //Acedemy
    course: "//div[contains(@class,'navigation-submenu')]//a[@title='Courses']",
    fundamentalCourses: "//div[contains(@class,'navigation-submenu')] //a[@title='Fundamental courses']",
    certificationCourse: "//div[contains(@class,'navigation-submenu')] //a[@title='Certification courses']",
    acne: "(//div[contains(@class,'navigation-submenu')] //a[@title='Acne'])[2]",
    aging: "(//div[contains(@class,'navigation-submenu')] //a[@title='Aging'])[2]",
    hyperPigmentation: "//div[contains(@class,'navigation-submenu')] //a[@title='Hyperpigmentation']",
    sensitiveSkin: "//div[contains(@class,'navigation-submenu')] //a[@title='Sensitive skin']",
    businessBuilding: "//div[contains(@class,'navigation-submenu')] //a[@title='Business building']",
    peelApplicationVideos: "//div[contains(@class,'navigation-submenu')] //a[@title='Peel application videos']",
    multiCulturalSkin: "//div[contains(@class,'navigation-submenu')] //a[@title='Multicultural skin']",
    viewAllCourses: "//div[contains(@class,'navigation-submenu')] //a[@aria-label='View All : Courses']",




    learn: "//div[contains(@class,'navigation-submenu')] //a[@title='Learn']",
    skinConcerns: "//div[contains(@class,'navigation-submenu')] //ul //a[@title='Skin concerns']",
    skinType: "//div[contains(@class,'navigation-submenu')] //ul //a[@title='Skin types']",
    skinIntelligence: "//div[contains(@class,'navigation-submenu')] //ul //a[@title='Skin intelligence']",
    professionalPeels: "//div[contains(@class,'navigation-submenu')] //ul //a[@title='Professional peels']",
    myOnlineCourses: "//div[contains(@class,'navigation-submenu')] //ul //a[@title='My online courses']",


    educationMemberships: "//div[contains(@class,'navigation-submenu')] //a[@title='Education Memberships']",
    allAccessMembership: "//div[contains(@class,'navigation-submenu')] //a[@title='All-access membership']",
    acneMembership: "//div[contains(@class,'navigation-submenu')] //a[@title='Acne membership']",
    agingMembership: "//div[contains(@class,'navigation-submenu')] //a[@title='Aging membership']",
    hyperPigmentationMembership: "//div[contains(@class,'navigation-submenu')] //a[@title='Hyperpigmentation membership']",
    sensitiveSkinMembership: "//div[contains(@class,'navigation-submenu')] //a[@title='Sensitive skin membership']",
    enhancingYourServices: "//div[contains(@class,'navigation-submenu')] //a[@title='Enhancing your services']",
    multiCulturalSkinMembership: "//div[contains(@class,'navigation-submenu')] //a[@title='Multi-cultural skin membership']",
    viewAllEducationMembership: "//div[contains(@class,'navigation-submenu')] //a[@aria-label='View All : Education Memberships']",

    // Events
    calendar: "//div[contains(@class,'navigation-submenu')]//div[text()='Calendar']",
    treatmentTuesdays: "//div[contains(@class,'navigation-submenu')]//a[@title='Treatment Tuesdays']",
    nationalSeminars: "//div[contains(@class,'navigation-submenu')]//a[@title='National seminars']",

    // About
    about: "//div[contains(@class,'navigation-submenu')]//div[text()='About ']",
    ourStory: "//div[contains(@class,'navigation-submenu')]//a[@title='Our Story']",
    culture: "//div[contains(@class,'navigation-submenu')]//a[@title='Culture']",
    ourPeelLegacy: "//div[contains(@id, 'navigation-submenu-wrapper-4')]//a[@title='Our peel legacy']",


    customerServiceText: "//div[contains(@class,'navigation-submenu')]//div[text()='Customer Service']",
    faq: "//div[contains(@class,'navigation-submenu')]//a[@title='FAQs']",
    returnAndExchange: "//div[contains(@class,'navigation-submenu')]//a[@title='Returns & exchanges']",
    shippingTerms: "//div[contains(@class,'navigation-submenu')]//a[@title='Shipping terms']",
    contactUs: "//div[contains(@id,'navigation-submenu-wrapper-4')]//a[@title='Contact us']",
    subscription: "//div[contains(@id,'navigation-submenu-wrapper-4')]//a[@title='Subscription']",

    // Business tools
    marketingMaterials: "//div[contains(@class,'navigation-submenu')]//div[text()='Marketing materials']",
    contentHub: "//div[contains(@class,'navigation-submenu')]//a[@title='Content Hub']",

    microSites: "//div[contains(@class,'navigation-submenu')]//a[@title='Microsites']",
    page_1: "//div[contains(@class,'navigation-submenu')]//a[@title='Page 1']",
    page_2: "//div[contains(@class,'navigation-submenu')]//a[@title='Page 2']",
    micrositeLearnMore: "//div[contains(@class,'navigation-submenu')]//a[text()='Learn More']",

    //Student
    studentProducts: "//div[contains(@class,'navigation-submenu')]//div[text()='Student Products']",
    viewAllStudents: "//div[contains(@class,'navigation-submenu')]//a[@aria-label='View All : Student Products']",


    studentCourses: "//div[contains(@class,'navigation-submenu')]//div[text()='Student Courses']",
    enhancingStudentCurriculm: "//div[contains(@class,'navigation-submenu')]//a[@title='Enhancing Student Curriculum']",


    studentStore: "//div[contains(@class,'navigation-submenu')]//div[text()='Student Store']",
    FAQ: `//div[contains(@class,'navigation-submenu')]//a[@aria-label='FAQ : Student Store']`,

    searchProductsTextbox: `//input[@placeholder ="Search"]`,
    searchIconforTextbox: `//button[@aria-label="search-icon"]`,
    utilityBanner: "nav.utility-nav-wrapper",
    marketingIcon: "div.marketing-icon",
    marketingContentInformation: `div.container div.text-sm p:text-is("Get a free full-sized HydraMatte with your first purchase on our new professional website!")`,
    navigationHeader: `div.container.navigation-header`,
    homePage: `main#skipNavigation span:text-is("Home")`,
    allProductTitle: `//div[normalize-space()='All Products']`,
    bestSeller: `div.product-carousel-title h2`,
    shopSubMenuLinksExpand: `div.navigation-menu ul li a:text-is("Shop") + div#navigation-submenu-wrapper-1 div.navigation-submenu-container`,
    skinTypePageTitle: `div.sidebar-left h1:text-is("Skin Types")`,
    skinByConcernsTitle: `div.sidebar-left h1:text-is("Concerns")`,
    allCoursePageTitle: `section.container div h1:text-is("All Courses")`,
    fundamentalCourseTitle: `section.container div h1:text-is("Fundamental Courses")`,
    certificationCourseTitle: `section.container div h1:text-is("Certification Courses")`,
    acnePageTitle: `section.container div h1:text-is("Acne")`,
    agingPageTitle: `section.container div h1:text-is("Aging")`,
    hyperpigmentationPageTitle: `section.container div h1:text-is("Hyperpigmentation")`,
    sensitiveSkinPageTitle: `section.container div h1:text-is("Sensitive Skin")`,
    businessBuildingPageTitle: `section.container div h1:text-is("Business Building")`,
    peelApplicationVideosPageTitle: `section.container div h1:text-is("Peel application videos")`,
    multiculturalSkinPageTitle: `section.container div h1:text-is("Multicultural Skin")`,
    educationMembershipsPageTitle: `section.container div h1:text-is("Education Memberships")`,
    allAccessMembershipPageTitle: `div.container h1:text-is("All Access Membership")`,
    acneMembershipPageTitle: `div.container h1:text-is("Acne Membership")`,
    agingMembershipPageTitle: `div.container h1:text-is("Aging Skin Membership")`,
    hyperpigmentationMembershipPageTitle: `div.container h1:text-is("Hyperpigmentation Membership")`,
    sensitiveSkinMembershipPageTitle: `div.container h1:text-is("Sensitive Skin Membership")`,
    enhancingYourServicesMembershipPageTitle: `div.container h1:text-is("Enhancing your Services Membership")`,
    multiCulturalSkinMembershipPageTitle: `div.container h1:text-is("Multicultural Skin Membership")`,
    //subtotal for empty cart 
    emptyCartSubTotal : `//div[contains(@class,'global-cart-subtotal')] /span[text()="$0.00"]`,
    aboutPCASKINHeader:`div.container h3:text-is("About PCA SKIN")`,
    ourStoryPageHeader: `div.container h1:text-is("Our journey of improving people’s lives")`,
    culturePageHeader: `div.container h1:text-is("our core values")`,
    ourPeelLegacyHeader: `div.container h1:text-is("Your Chemical Peel Authority")`,
    faqPageHeader:`div.container div:text-is("FAQs")`,
    returnExchangePageHeader: `div.container h1:text-is("CP Skin Health Return Policy")`,
    shippingTermsPageHeader:`div.container h1:text-is("Shipping Terms")`,
    contactUsPageHeader: `div.container h1:text-is("Contact Us")`,
    subscriptionPageHeader:`div.container h1:text-is("PCA SKIN Subscriptions")`,
    businessToolPageHeader: `section.container div h1:text-is("Business Building")`,
    studentMenuListAtLastPosition:`div.navigation-menu nav ul li.navigation-menu-list >>nth=6`,
    navigationMenuBar:`div.navigation-menu`,
    navigationActionBar:`div.navigation-actions`,
    studentOnly: `div.container button div.text-sm`,
    studentInfoPageTitle:`div.course-info h1:text-is("Enhancing Student Curriculum")`,
    afterLoginUserIconCompanyProfile: `div#user-account div.global-account-menu a[title='Company Profile']`,
    afterLoginUserIconCompanyUsers: `div#user-account div.global-account-menu a[title='Company Users']`,
    afterLoginUserIconDropshipAddresses: `div#user-account div.global-account-menu a[title='Dropship Addresses']`,
    afterLoginUserIconPaymentMethods: `div#user-account div.global-account-menu a[title='Payment Methods']`,
    afterLoginUserIconFavorites: `div#user-account div.global-account-menu a[title='Favorites']`,
    userIconOverview: `div#user-account div.global-account-menu a[title='Overview'] span`,
    userIconOrders: `div#user-account div.global-account-menu a[title='Orders'] span`,
    userIconInvoices: `div#user-account div.global-account-menu a[title='Invoices'] span`,
    userIconSubscriptions: `div#user-account div.global-account-menu a[title='Subscriptions'] span`,
    userIconEducation: `div#user-account div.global-account-menu a[title='Education'] span`,
    userIconPersonalProfile: `div#user-account div.global-account-menu a[title='Personal Profile'] span`,
    userIconCompanyProfile: `div#user-account div.global-account-menu a[title='Company Profile'] span`,
    userIconCompanyUsers: `div#user-account div.global-account-menu a[title='Company Users'] span`,
    userIconDropshipAddresses: `div#user-account div.global-account-menu a[title='Dropship Addresses'] span`,
    userIconPaymentMethods: `div#user-account div.global-account-menu a[title='Payment Methods'] span`,
    userIconFavorites: `div#user-account div.global-account-menu a[title='Favorites'] span`,
    accountPage:`div.container div p:text-is("Account")`,
    userAccountLogoutIcon: `div#user-account div.global-account-menu button span`,
    cartDropdown:`div.navigation-cart div.global-cart-container`,
    searchBtn:"//button[contains(@class,'search-icon')]",
    coursesPageTitle: `div.container h1:text-is("Courses")`,
}

// NavigationHeaderLocators.ts