export const PaymentMethodsLocators = {
    paymentMethodsHeading: `//h2[contains(@class,'heading') and text()='Payment Methods']`,
    addPaymentMethodsHeading: `//h2[contains(@class,'heading') and text()='Add Payment Method']`,
    addPaymentMethodBtn: `//button[text()='Add New Payment Method']`,
    newPaymentForm: `//form[contains(@class,'new-payment-form')]`,
    cardNumberLabel: `//form[contains(@class,'new-payment-form')]//label[@for='cNumber']`,
    expirationLabel: `//form[contains(@class,'new-payment-form')]//label[@for='cExpiry']`,
    CVVLabel: `//form[contains(@class,'new-payment-form')]//label[@for='cvc']`,
    fullNameLabel: `//label[@for="Field-nameInput"]`,
    addressLineLabel: `//label[@for="Field-addressLine1Input"]`,
    savePaymentMethodBtn: `//button[text()='Save Payment Method']`,
    closeBtn: `//button[text()='Close']`,
    cardNumberField: `//input[@name="cardnumber" and @placeholder]`,
    expirationField: `//input[@name="exp-date"]`,
    CVVField: `//div[@id="cvc"]`,
    fullNameField: `//input[@id="Field-nameInput"]`,
    addressLineField: `//input[@id="Field-addressLine1Input"]`,
    errorToast: `//div[@id="add-payment-method-error"]`,
    errorText: `//div[@id="add-payment-method-error"]//div[text()='Please enter valid card details']`,
    errorToastCloseBtn: `//button[contains(@class,"Toastify__close-button")]`,
    setAsDefaultText:`//label[@for="set-as-default"]`,
    setAsDefaultCheckBox:`//input[@id="set-as-default"]`,
}