export const filters = {
    filtersByproductsHeading: `//h3[contains(@class, 'heading') and text()='Products']`,
    filtersBycategoryHeading: `//h3[contains(@class, 'heading') and text()='Category']`,
    filtersByageRangeHeading: `//h3[contains(@class, 'heading') and text()='Age Range']`,
    filtersByBristleSoftnessHeading: `//h3[contains(@class, 'heading') and text()='Bristle Softness']`,
    filtersByBrushHeadsize: `//h3[contains(@class, 'heading') and text()='Brush Headsize']`,
    filtersByFormula: `//h3[contains(@class, 'heading') and text()='Formula']`,
    filtersByPatientCondition: `//h3[contains(@class, 'heading') and text()='Patient Condition']`,
    filtersByVariant: `//h3[contains(@class, 'heading') and text()='Variant']`,
    filtersByRX: `//h3[contains(@class, 'heading') and text()='RX']`,

    filtersByProductsdownArrow: `//h3[text()='Products']/following-sibling::span[@class='self-center arrow-downwards']`,
    filtersByCategorydownArrow: `//h3[text()='Category']/following-sibling::span[@class='self-center arrow-downwards']`,
    filtersByageRangedownArrow: `//h3[text()='Age Range']/following-sibling::span[@class='self-center arrow-downwards']`,
    filtersByformuladownArrow: `//h3[text()='Formula']/following-sibling::span[@class='self-center arrow-downwards']`,
    filtersByPatientConditiondownArrow: `//h3[text()='Patient Condition']/following-sibling::span[@class='self-center arrow-downwards']`,
    filtersByRXdownArrow: `//h3[text()='RX']/following-sibling::span[@class='self-center arrow-downwards']`,
    filtersByVariantdownArrow: `//h3[text()='Variant']/following-sibling::span[@class='self-center arrow-downwards']`,
    filtersByBristleSoftnessdownArrow: `//h3[text()='Bristle Softness']/following-sibling::span[@class='self-center arrow-downwards']`,
    filtersByBrushHeadsizedownArrow: `//h3[text()='Brush Headsize']/following-sibling::span[@class='self-center arrow-downwards']`,

    filtersProductsupArrow: `//h3[text()='Products']/following-sibling::span[@class='self-center arrow-upwards']`,
    filtersCategoryupArrow: `//h3[text()='Category']/following-sibling::span[@class='self-center arrow-upwards']`,
    filtersAgeRangeupArrow: `//h3[text()='Age Range']/following-sibling::span[@class='self-center arrow-upwards']`,
    filtersFormulaupArrow: `//h3[text()='Formula']/following-sibling::span[@class='self-center arrow-upwards']`,
    filtersPatientConditionupArrow: `//h3[text()='Patient Condition']/following-sibling::span[@class='self-center arrow-upwards']`,
    filtersRXupArrow: `//h3[text()='RX']/following-sibling::span[@class='self-center arrow-upwards']`,
    filtersVariantupArrow: `//h3[text()='Variant']/following-sibling::span[@class='self-center arrow-upwards']`,
    filtersBristleSoftnessupArrow: `//h3[text()='Bristle Softness']/following-sibling::span[@class='self-center arrow-upwards']`,
    filtersBrushHeadsizeupArrow: `//h3[text()='Brush Headsize']/following-sibling::span[@class='self-center arrow-upwards']`,



    filtersCategoryColgatePrevidentSeriescheckBoxes: `//div[@data-accordion-component="AccordionItemPanel"]//input[@title="Colgate® Prevident Series"]`,
    filtersCategoryColgateGelKamcheckBoxes: `//div[@data-accordion-component="AccordionItemPanel"]//input[@title="Colgate® Gel-Kam"]`,
    filtersAgeRangeAdultcheckBoxes: `//div[@data-accordion-component="AccordionItemPanel"]//input[@title="Adult"]`,
    filtersFormulaToothPastecheckBoxes: `//div[@data-accordion-component="AccordionItemPanel"]//input[@title="Toothpaste"]`,
    filtersFormulaGelcheckBoxes: `//div[@data-accordion-component="AccordionItemPanel"]//input[@title="Gel"]`,
    filtersFormulaVarnishcheckBoxes: `//div[@data-accordion-component="AccordionItemPanel"]//input[@title="Varnish"]`,
    filtersPatientConditionSensitivitycheckBoxes: `//div[@data-accordion-component="AccordionItemPanel"]//input[@title="Sensitivity"]`,
    filtersPatientConditionOrthocheckBoxes: `//div[@data-accordion-component="AccordionItemPanel"]//input[@title="Ortho"]`,
    filtersPatientConditionGingivitisPeriocheckBoxes: `//div[@data-accordion-component="AccordionItemPanel"]//input[@title="Gingivitis/Perio"]`,
    filtersPatientConditionCariesAdultcheckBoxes: `//div[@data-accordion-component="AccordionItemPanel"]//input[@title="Caries Adult"]`,
    filtersPatientConditionErosioncheckBoxes: `//div[@data-accordion-component="AccordionItemPanel"]//input[@title="Erosion"]`,
    filtersPatientConditionDryMouthcheckBoxes: `//div[@data-accordion-component="AccordionItemPanel"]//input[@title="Dry Mouth"]`,
    filtersPatientConditionImplantscheckBoxes: `//div[@data-accordion-component="AccordionItemPanel"]//input[@title="Implants"]`,
    filtersPatientConditionCariesKidscheckBoxes: `//div[@data-accordion-component="AccordionItemPanel"]//input[@title="Caries Kids"]`,
    filtersPatientConditionChemotherapyRadiationTreatmentcheckBoxes: `//div[@data-accordion-component="AccordionItemPanel"]//input[@title="Chemotherapy/Radiation Treatment"]`,
    filtersRXPrescriptioncheckBoxes: `//div[@data-accordion-component="AccordionItemPanel"]//input[@title="Prescription"]`,
    filtersRXNonPrescriptioncheckBoxes: `//div[@data-accordion-component="AccordionItemPanel"]//input[@title="Non-Prescription"]`,
    filtersVarientImprintedcheckBoxes: `//div[@data-accordion-component="AccordionItemPanel"]//input[@title="Imprinted"]`,
    filtersVarientNonImprintedcheckBoxes: `//div[@data-accordion-component="AccordionItemPanel"]//input[@title="Non-Imprinted"]`,
    filtersBristleSoftnessExtraSoftcheckBoxes: `//div[@data-accordion-component="AccordionItemPanel"]//input[@title="Extra Soft"]`,
    filtersBristleSoftnessSoftcheckBoxes: `//div[@data-accordion-component="AccordionItemPanel"]//input[@title="Soft"]`,
    filtersBrushHeadsizeCompactcheckBoxes: `//div[@data-accordion-component="AccordionItemPanel"]//input[@title="Compact"]`,
    filtersBrushHeadsizeUltraCompactcheckBoxes: `//div[@data-accordion-component="AccordionItemPanel"]//input[@title="Ultra Compact"]`,
    filtersBrushHeadsizeSmallAges07checkBoxes: `//div[@data-accordion-component="AccordionItemPanel"]//input[@title="Small (Ages 0-7)"]`,
    filtersBrushHeadsizeFullHeadcheckBoxes: `//div[@data-accordion-component="AccordionItemPanel"]//input[@title="Full Head"]`,
    filtersBrushHeadsizeYouthAges5checkBoxes: `//div[@data-accordion-component="AccordionItemPanel"]//input[@title="Youth (Ages 5+)"]`,
    filtersBrushHeadsizeJuniorAges04checkBoxes: `//div[@data-accordion-component="AccordionItemPanel"]//input[@title="Junior (Ages 0 - 4)"]`,

    filtersProductsAllProducts: `//div[@class="accordion__item"]//button[text()="All Products"]`,
    filtersProductsFloss: `//div[@class="accordion__item"]//button[text()="Floss"]`,
    filtersProductsFluorideTherapy: `//div[@class="accordion__item"]//button[text()="Fluoride Therapy"]`,
    filtersProductsMouthWash: `//div[@class="accordion__item"]//button[text()="Mouthwash"]`,
    filtersProductsOralRinses: `//div[@class="accordion__item"]//button[text()="Oral Rinses"]`,
    filtersProductsToothbrush: `//div[@class="accordion__item"]//button[text()="Toothbrush"]`,
    filtersProductsSeeMoreCategories: `//div[@class="accordion__item"]//button[text()="See More Categories"]`,
    filtersProductsWhitening: `//div[@class="accordion__item"]//button[text()="Whitening"]`,


    filtersAgeRangeAdultcheckBoxeslabel: `//div[@data-accordion-component="AccordionItemPanel"]//label[text()="Adult"]`,
    filtersCategoryColgatePrevidentSerieslabel: `//div[@data-accordion-component="AccordionItemPanel"]//label[text()="Colgate® Prevident Series"]`,
    filtersCategoryColgateGelKamcheckBoxeslabel: `//div[@data-accordion-component="AccordionItemPanel"]//label[text()="Colgate® Gel-Kam"]`,
    filtersFormulaToothpastecheckBoxeslabel: `//div[@data-accordion-component="AccordionItemPanel"]//label[text()="Toothpaste"]`,
    filtersFormulaGelcheckBoxeslabel: `//div[@data-accordion-component="AccordionItemPanel"]//label[text()="Gel"]`,
    filtersFormulaVarnishcheckBoxeslabel: `//div[@data-accordion-component="AccordionItemPanel"]//label[text()="Varnish"]`,
    filtersPatientConditionSensitivitycheckBoxeslabel: `//div[@data-accordion-component="AccordionItemPanel"]//label[text()="Sensitivity"]`,
    filtersPatientConditionOrthocheckBoxeslabel: `//div[@data-accordion-component="AccordionItemPanel"]//label[text()="Ortho"]`,
    filtersPatientConditionGingivitisPeriocheckBoxeslabel: `//div[@data-accordion-component="AccordionItemPanel"]//label[text()="Gingivitis/Perio"]`,
    filtersPatientConditionCariesAdultcheckBoxeslabel: `//div[@data-accordion-component="AccordionItemPanel"]//label[text()="Caries Adult"]`,
    filtersPatientConditionErosioncheckBoxeslabel: `//div[@data-accordion-component="AccordionItemPanel"]//label[text()="Erosion"]`,
    filtersPatientConditionDryMouthcheckBoxeslabel: `//div[@data-accordion-component="AccordionItemPanel"]//label[text()="Dry Mouth"]`,
    filtersPatientConditionImplantscheckBoxeslabel: `//div[@data-accordion-component="AccordionItemPanel"]//label[text()="Implants"]`,
    filtersPatientConditionCariesKidscheckBoxeslabel: `//div[@data-accordion-component="AccordionItemPanel"]//label[text()="Caries Kids"]`,
    filtersPatientConditionChemotherapyRadiationTreatmentcheckBoxeslabel: `//div[@data-accordion-component="AccordionItemPanel"]//label[text()="Chemotherapy/Radiation Treatment"]`,
    filtersRXPrescriptioncheckBoxeslabel: `//div[@data-accordion-component="AccordionItemPanel"]//label[text()="Prescription"]`,
    filtersRXNonPrescriptioncheckBoxeslabel: `//div[@data-accordion-component="AccordionItemPanel"]//label[text()="Non-Prescription"]`,
    filtersVarientImprintedcheckBoxeslabel: `//div[@data-accordion-component="AccordionItemPanel"]//label[text()="Imprinted"]`,
    filtersVarientNonImprintedcheckBoxeslabel: `//div[@data-accordion-component="AccordionItemPanel"]//label[text()="Non-Imprinted"]`,
    filtersBristleSoftnessExtraSoftcheckBoxeslabel: `//div[@data-accordion-component="AccordionItemPanel"]//label[text()="Extra Soft"]`,
    filtersBristleSoftnessSoftcheckBoxeslabel: `//div[@data-accordion-component="AccordionItemPanel"]//label[text()="Soft"]`,
    filtersBrushHeadsizeCompactcheckBoxeslabel: `//div[@data-accordion-component="AccordionItemPanel"]//label[text()="Compact"]`,
    filtersBrushHeadsizeUltraCompactcheckBoxeslabel: `//div[@data-accordion-component="AccordionItemPanel"]//label[text()="Ultra Compact"]`,
    filtersBrushHeadsizeSmallAges07checkBoxeslabel: `//div[@data-accordion-component="AccordionItemPanel"]//label[text()="Small (Ages 0-7)"]`,
    filtersBrushHeadsizeFullHeadcheckBoxeslabel: `//div[@data-accordion-component="AccordionItemPanel"]//label[text()="Full Head"]`,
    filtersBrushHeadsizeYouthAges5checkBoxeslabel: `//div[@data-accordion-component="AccordionItemPanel"]//label[text()="Youth (Ages 5+)"]`,
    filtersBrushHeadsizeJuniorAges04checkBoxeslabel: `//div[@data-accordion-component="AccordionItemPanel"]//label[text()="Junior (Ages 0 - 4)"]`,


    filtersAppliedFloss: `//div[contains(@class,'flex-wrap items')]//div[text()='Floss']`,
    filtersAppliedFluorideTherapy: `//div[contains(@class,'flex-wrap items')]//div[text()='Fluoride Therapy']`,
    filtersAppliedMouthwash: `//div[contains(@class,'flex-wrap items')]//div[text()='Mouthwash']`,
    filtersAppliedOralRinses: `//div[contains(@class,'flex-wrap items')]//div[text()='Oral Rinses']`,
    filtersAppliedToothbrush: `//div[contains(@class,'flex-wrap items')]//div[text()='Toothbrush']`,
    filtersAppliedWhitening: `//div[contains(@class,'flex-wrap items')]//div[text()='Whitening']`,
    filtersAppliedKidsAndTweens: `//div[contains(@class,'flex-wrap items')]//div[text()='Kids & Tweens']`,
    filtersAppliedColgatePrevidentSeries: `//div[contains(@class,'flex-wrap items')]//div[text()='Colgate® Prevident Series']`,
    filtersAppliedPremium: `//div[contains(@class,'flex-wrap items')]//div[text()='Premium']`,
    filtersAppliedClassic: `//div[contains(@class,'flex-wrap items')]//div[text()='Classic']`,
    filtersAppliedTakeHome: `//div[contains(@class,'flex-wrap items')]//div[text()='Take Home']`,
    filtersAppliedColgatePeroxylRinse: `//div[contains(@class,'flex-wrap items')]//div[text()='Colgate® Peroxyl® Rinse']`,
    filtersAppliedInOffice: `//div[contains(@class,'flex-wrap items')]//div[text()='In Office']`,
    filtersAppliedColgatePhosFlurRinse: `//div[contains(@class,'flex-wrap items')]//div[text()='Colgate® Phos-Flur ® Rinse']`,
    filtersAppliedColgatePeriogardRinse: `//div[contains(@class,'flex-wrap items')]//div[text()='Colgate® Periogard Rinse']`,
    filtersAppliedColgateGelKam: `//div[contains(@class,'flex-wrap items')]//div[text()='Colgate® Gel-Kam']`,
    filtersAppliedAdult: `//div[contains(@class,'flex-wrap items')]//div[text()='Adult']`,
    filtersApplied02yearsold: `//div[contains(@class,'flex-wrap items')]//div[text()='0 - 2 years old']`,
    filtersApplied34yearsold: `//div[contains(@class,'flex-wrap items')]//div[text()='3 - 4 years old']`,
    filtersApplied57yearsold: `//div[contains(@class,'flex-wrap items')]//div[text()='5 - 7 years old']`,
    filtersApplied812yearsold: `//div[contains(@class,'flex-wrap items')]//div[text()='8 - 12 years old']`,
    filtersAppliedExtraSoft: `//div[contains(@class,'flex-wrap items')]//div[text()='Extra Soft']`,
    filtersAppliedSoft: `//div[contains(@class,'flex-wrap items')]//div[text()='Soft']`,
    filtersAppliedCompact: `//div[contains(@class,'flex-wrap items')]//div[text()='Compact']`,
    filtersAppliedUltraCompact: `//div[contains(@class,'flex-wrap items')]//div[text()='Ultra Compact']`,
    filtersAppliedSmallAges07: `//div[contains(@class,'flex-wrap items')]//div[text()='Small (Ages 0-7)']`,
    filtersAppliedFullHead: `//div[contains(@class,'flex-wrap items')]//div[text()='Full Head']`,
    filtersAppliedYouthAges5: `//div[contains(@class,'flex-wrap items')]//div[text()='Youth (Ages 5+)']`,
    filtersAppliedJuniorAges04: `//div[contains(@class,'flex-wrap items')]//div[text()='Junior (Ages 0 - 4)']`,
    filtersAppliedToothpaste: `//div[contains(@class,'flex-wrap items')]//div[text()='Toothpaste']`,
    filtersAppliedGel: `//div[contains(@class,'flex-wrap items')]//div[text()='Gel']`,
    filtersAppliedVarnish: `//div[contains(@class,'flex-wrap items')]//div[text()='Varnish']`,
    filtersAppliedSensitivity: `//div[contains(@class,'flex-wrap items')]//div[text()='Sensitivity']`,
    filtersAppliedOrtho: `//div[contains(@class,'flex-wrap items')]//div[text()='Ortho']`,
    filtersAppliedGingivitisPerio: `//div[contains(@class,'flex-wrap items')]//div[text()='Gingivitis/Perio']`,
    filtersAppliedCariesAdult: `//div[contains(@class,'flex-wrap items')]//div[text()='Caries Adult']`,
    filtersAppliedErosion: `//div[contains(@class,'flex-wrap items')]//div[text()='Erosion']`,
    filtersAppliedDryMouth: `//div[contains(@class,'flex-wrap items')]//div[text()='Dry Mouth']`,
    filtersAppliedImplants: `//div[contains(@class,'flex-wrap items')]//div[text()='Implants']`,
    filtersAppliedCariesKids: `//div[contains(@class,'flex-wrap items')]//div[text()='Caries Kids']`,
    filtersAppliedChemotherapyRadiationTreatment: `//div[contains(@class,'flex-wrap items')]//div[text()='Chemotherapy/Radiation Treatment']`,
    filtersAppliedImprinted: `//div[contains(@class,'flex-wrap items')]//div[text()='Imprinted']`,
    filtersAppliedNonImprinted: `//div[contains(@class,'flex-wrap items')]//div[text()='Non-Imprinted']`,
    filtersAppliedPrescription: `//div[contains(@class,'flex-wrap items')]//div[text()='Prescription']`,
    filtersAppliedNonPrescription: `//div[contains(@class,'flex-wrap items')]//div[text()='Non-Prescription']`,



    filtersAppliedFlosscloseBtn: `//button[contains(@aria-label,"Floss")]//div[@class="cross-icon-active"]`,
    filtersAppliedFluorideTherapycloseBtn: `//button[contains(@aria-label,"Fluoride Therapy")]//div[@class="cross-icon-active"]`,
    filtersAppliedMouthwashcloseBtn: `//button[contains(@aria-label,"Mouthwash")]//div[@class="cross-icon-active"]`,
    filtersAppliedOralRinsescloseBtn: `//button[contains(@aria-label,"Oral Rinses")]//div[@class="cross-icon-active"]`,
    filtersAppliedToothbrushcloseBtn: `//button[contains(@aria-label,"Toothbrush")]//div[@class="cross-icon-active"]`,
    filtersAppliedWhiteningcloseBtn: `//button[contains(@aria-label,"Whitening")]//div[@class="cross-icon-active"]`,
    filtersAppliedKidsAndTweenscloseBtn: `//button[contains(@aria-label,"Kids & Tweens")]//div[@class="cross-icon-active"]`,
    filtersAppliedColgatePrevidentSeriescloseBtn: `//button[contains(@aria-label,"Colgate® Prevident Series")]//div[@class="cross-icon-active"]`,
    filtersAppliedPremiumcloseBtn: `//button[contains(@aria-label,"Premium")]//div[@class="cross-icon-active"]`,
    filtersAppliedClassiccloseBtn: `//button[contains(@aria-label,"Classic")]//div[@class="cross-icon-active"]`,
    filtersAppliedTakeHomecloseBtn: `//button[contains(@aria-label,"Take Home")]//div[@class="cross-icon-active"]`,
    filtersAppliedColgatePeroxylRinsecloseBtn: `//button[contains(@aria-label,"Colgate® Peroxyl® Rinse")]//div[@class="cross-icon-active"]`,
    filtersAppliedInOfficecloseBtn: `//button[contains(@aria-label,"In Office")]//div[@class="cross-icon-active"]`,
    filtersAppliedColgatePhosFlurRinsecloseBtn: `//button[contains(@aria-label,"Colgate® Phos-Flur ® Rinse")]//div[@class="cross-icon-active"]`,
    filtersAppliedColgatePeriogardRinsecloseBtn: `//button[contains(@aria-label,"Colgate® Periogard Rinse")]//div[@class="cross-icon-active"]`,
    filtersAppliedColgateGelKamcloseBtn: `//button[contains(@aria-label,"Colgate® Gel-Kam")]//div[@class="cross-icon-active"]`,
    filtersAppliedAdultcloseBtn: `//button[contains(@aria-label,"adult")]//div[@class="cross-icon-active"]`,
    filtersApplied02yearsoldcloseBtn: `//button[contains(@aria-label,"0---2-years-old")]//div[@class="cross-icon-active"]`,
    filtersApplied34yearsoldcloseBtn: `//button[contains(@aria-label,"3---4-years-old")]//div[@class="cross-icon-active"]`,
    filtersApplied57yearsoldcloseBtn: `//button[contains(@aria-label,"5---7-years-old")]//div[@class="cross-icon-active"]`,
    filtersApplied812yearsoldcloseBtn: `//button[contains(@aria-label,"8---12-years-old")]//div[@class="cross-icon-active"]`,
    filtersAppliedExtraSoftcloseBtn: `//button[contains(@aria-label,"extra-soft")]//div[@class="cross-icon-active"]`,
    filtersAppliedSoftcloseBtn: `//button[contains(@aria-label," undefined soft")]//div[@class="cross-icon-active"]`,
    filtersAppliedCompactcloseBtn: `//button[contains(@aria-label," undefined compact")]//div[@class="cross-icon-active"]`,
    filtersAppliedUltraCompactcloseBtn: `//button[contains(@aria-label,"ultra-compact")]//div[@class="cross-icon-active"]`,
    filtersAppliedSmallAges07closeBtn: `//button[contains(@aria-label,"small--ages-20-7")]//div[@class="cross-icon-active"]`,
    filtersAppliedFullHeadcloseBtn: `//button[contains(@aria-label,"full-head")]//div[@class="cross-icon-active"]`,
    filtersAppliedYouthAges5closeBtn: `//button[contains(@aria-label,"youth--ages-5")]//div[@class="cross-icon-active"]`,
    filtersAppliedJuniorAges04closeBtn: `//button[contains(@aria-label,"junior--ages-0---4")]//div[@class="cross-icon-active"]`,
    filtersAppliedToothpastecloseBtn: `//button[contains(@aria-label,"toothpaste")]//div[@class="cross-icon-active"]`,
    filtersAppliedGelcloseBtn: `//button[contains(@aria-label,"gel")]//div[@class="cross-icon-active"]`,
    filtersAppliedVarnishcloseBtn: `//button[contains(@aria-label,"varnish")]//div[@class="cross-icon-active"]`,
    filtersAppliedSensitivitycloseBtn: `//button[contains(@aria-label,"sensitivity")]//div[@class="cross-icon-active"]`,
    filtersAppliedOrthocloseBtn: `//button[contains(@aria-label,"ortho")]//div[@class="cross-icon-active"]`,
    filtersAppliedGingivitisPeriocloseBtn: `//button[contains(@aria-label,"gingivitis-perio")]//div[@class="cross-icon-active"]`,
    filtersAppliedCariesAdultcloseBtn: `//button[contains(@aria-label,"caries-adult")]//div[@class="cross-icon-active"]`,
    filtersAppliedErosioncloseBtn: `//button[contains(@aria-label,"erosion")]//div[@class="cross-icon-active"]`,
    filtersAppliedDryMouthcloseBtn: `//button[contains(@aria-label,"dry-mouth")]//div[@class="cross-icon-active"]`,
    filtersAppliedImplantscloseBtn: `//button[contains(@aria-label,"implants")]//div[@class="cross-icon-active"]`,
    filtersAppliedCariesKidscloseBtn: `//button[contains(@aria-label,"caries-kids")]//div[@class="cross-icon-active"]`,
    filtersAppliedChemotherapyRadiationTreatmentcloseBtn: `//button[contains(@aria-label,"chemotherapy-radiation-treatment")]//div[@class="cross-icon-active"]`,
    filtersAppliedImprintedcloseBtn: `//button[contains(@aria-label," undefined imprinted")]//div[@class="cross-icon-active"]`,
    filtersAppliedNonImprintedcloseBtn: `//button[contains(@aria-label,"non-imprinted")]//div[@class="cross-icon-active"]`,
    filtersAppliedPrescriptioncloseBtn: `//button[contains(@aria-label," undefined prescription")]//div[@class="cross-icon-active"]`,
    filtersAppliedNonPrescriptioncloseBtn: `//button[contains(@aria-label,"non-prescription")]//div[@class="cross-icon-active"]`,

    filtersclearFilterbtn: `//button[contains(@class,'clear-filters')]`
}
