export const RegistrationProfileLocators = {
    
    //Header
    registerYourProfile:"//h1[@id='registration-container_content_caption']",
    primaryContact:"//h2[normalize-space()='Primary Contact']",
    emailAddress:"//span[normalize-space()='Email Address']",
    emailAddressTextbox:"//input[@id='gigya-textbox-97993263193399070']",
    firstName:"//span[normalize-space()='First Name']",
    firstNameTextBox:"//input[@id='gigya-textbox-12712933737519516']",
    lastName: "//span[normalize-space()='Last Name']",
    lastNameTextBox:"//input[@id='gigya-textbox-127192338351018600']",
    password:"//label[@for='gigya-password-121651568326207260']//span[@class='gigya-label-text'][normalize-space()='Password']",
    passwordTextbox:"//input[@id='gigya-password-121651568326207260']",
    confirmPassword:"//span[normalize-space()='Confirm Password']",
    confirmPasswordText:"//input[@id='gigya-password-107907408090987540']",
    pcaSkinCheckbox:"//input[@id='gigya-checkbox-129625994634527090']",
    pcaSkinCheckboxEmpty:"//input[@class='gigya-input-checkbox fd-checkbox gigya-empty' and @id='gigya-checkbox-129625994634527090']",
    pcaSkinText:"//span[contains(text(),'Please send me exclusive offers and updates from P')]",
    privacyPolicyCheckboxEmpty:"//input[@class='gigya-input-checkbox fd-checkbox gigya-empty' and @id='gigya-checkbox-159180856793162560']",
    privacyPolicyCheckbox:"//input[@id='gigya-checkbox-159180856793162560']",
    privacyPolicyText:"//span[contains(text(),'Kindly explore our')]",
    privacyPolicyLink:"//a[normalize-space()='privacy policy']",
    createAccount:"//input[@value='Create Account']",
    emailErrorMsg: "//span[contains(@class,'gigya-error-msg-active ') and @data-bound-to='email']",
    firstNameErrorMsg: "//span[contains(@class,'gigya-error-msg-active ') and @data-bound-to='profile.firstName']",
    lastNameErrorMsg: "//span[contains(@class,'gigya-error-msg-active ') and @data-bound-to='profile.lastName']",
    passwordErrorMsg: "//span[contains(@class,'gigya-error-msg-active ') and @data-bound-to='password']",
    passwordReErrorMsg: "//span[contains(@class,'gigya-error-msg-active ') and @data-bound-to='passwordRetype']",
    emailFieldIsRequired: "//span[@data-bound-to='email' and text()='This field is required']",
    passwordFieldIsRequired : "//span[@data-bound-to='password' and text()='This field is required']",
    confirmPasswordFieldIsRequired : "//span[@data-bound-to='passwordRetype' and text()='This field is required']",
    emailIsValidCheckmark : "//input[contains(@class, 'gigya-input-text') and contains(@class, 'gigya-show-checkmark') and contains(@class, 'gigya-valid')]",
    passwordIsValidCheckmark : "//input[@placeholder='Password *' and contains(@class, 'gigya-show-checkmark')]",
    confirmPasswordIsValidCheckmark : "//input[@placeholder='Confirm Password *' and contains(@class, 'gigya-show-checkmark')]",
    privacyPolicyPageHeader : "//h1[normalize-space()='Privacy Policy']",
    passwordComplexityError : `//span[@data-bound-to='password' and text()='Password does not meet complexity requirements']`,
    }
    