export const StudentOnlyProductsLocators = {
    pcabreadCrumbLabel: `//ul[contains(@class,'breadcrumb-label')]`,
    pcaHeadingAllProducts: `//div[contains(@class, 'heading') and text()='All Products']`,

    filtersByproductsCategoryHeading: `//h3[contains(@class, 'heading') and text()='Products']`,
    filtersProductsAllProducts: `//div[contains(@class,'accordion-panel')]//button[text()='All Products']`,
    filtersProductsAntioxidants: `//div[contains(@class,'accordion-panel')]//button[text()='Antioxidants']`,
    filtersProductsBroadSpectrumSPF: `//div[contains(@class,'accordion-panel')]//button[text()='Broad Spectrum SPF']`,
    filtersProductsCleansersAndToners: `//div[contains(@class,'accordion-panel')]//button[text()='Cleansers & Toners']`,
    filtersProductsEyeNeckLip: `//div[contains(@class,'accordion-panel')]//button[text()='Eye, Neck, Lip']`,
    filtersProductsMasks: `//div[contains(@class,'accordion-panel')]//button[text()='Masks']`,
    filtersProductsShowAllCategories: `//div[contains(@class,'accordion-panel')]//button[text()='Show All Categories']`,

    filtersByProductsBestSellerHeading: `//h3[contains(@class,'heading')and text()='Best Seller']`,
    filtersBestSellerCheckBoxes: `//div[@data-accordion-component='AccordionItemPanel']// input[@title='Best Seller']`,
    filtersBestSellerCheckBoxesBestSellerlabel: `//label[text()='Best Seller']`,

    filtersByProductsProductTypesHeading: `//h3[contains(@class,'heading')and text()='Product Types']`,
    filtersProductsBackbarCheckBoxes: `//div[@data-accordion-component='AccordionItemPanel']// input[@title='Backbar']`,
    filtersProductsRetailCheckBoxes: `//div[@data-accordion-component='AccordionItemPanel']// input[@title='Retail']`,
    filtersProductsSampleCheckBoxes: `//div[@data-accordion-component='AccordionItemPanel']// input[@title='Sample']`,
    filtersProductsCheckBoxesBackbarLabel: `//label[text()='Backbar']`,
    filtersProductsCheckBoxesRetailLabel: `//label[text()='Retail']`,
    filtersProductsCheckBoxesSampleLabel: `//label[text()='Sample']`,

    filtersByProductsSkinConcernHeading: `//h3[contains(@class,'heading')and text()='Skin Concern']`,
    filtersProductsBrighteningCheckBoxes: `//div[@data-accordion-component='AccordionItemPanel']// input[@title='Brightening']`,
    filtersProductsAcneCheckBoxes: `//div[@data-accordion-component='AccordionItemPanel']// input[@title='Acne']`,
    filtersProductsAgingCheckBoxes: `//div[@data-accordion-component='AccordionItemPanel']// input[@title='Aging']`,
    filtersProductsDiscolorationsCheckBoxes: `//div[@data-accordion-component='AccordionItemPanel']// input[@title='Discolorations']`,
    filtersProductsPreventativeCheckBoxes: `//div[@data-accordion-component='AccordionItemPanel']// input[@title='Preventative']`,
    filtersProductsSensitiveSkinCheckBoxes: `//div[@data-accordion-component='AccordionItemPanel']// input[@title='Sensitive Skin']`,
    filtersProductsCheckBoxesBrighteningLabel: `//label[text()='Brightening']`,
    filtersProductsCheckBoxesAcneLabel: `//label[text()='Acne']`,
    filtersProductsCheckBoxesAgingLabel: `//label[text()='Aging']`,
    filtersProductsCheckBoxesDiscolorationsLabel: `//label[text()='Discolorations']`,
    filtersProductsCheckBoxesPreventativeLabel: `//label[text()='Preventative']`,
    filtersProductsCheckBoxesSensitiveSkinLabel: `//label[text()='Sensitive Skin']`,

    filtersByProductsSkinTypeHeading: `//h3[contains(@class,'heading')and text()='Skin Type']`,
    filtersProductsCombinationCheckBoxes: `//div[@data-accordion-component='AccordionItemPanel']// input[@title='Combination']`,
    filtersProductsDryCheckBoxes: `//div[@data-accordion-component='AccordionItemPanel']// input[@title='Dry']`,
    filtersProductsNormalCheckBoxes: `//div[@data-accordion-component='AccordionItemPanel']// input[@title='Normal']`,
    filtersProductsOilyCheckBoxes: `//div[@data-accordion-component='AccordionItemPanel']// input[@title='Oily']`,
    filtersProductsSensitiveCheckBoxes: `//div[@data-accordion-component='AccordionItemPanel']// input[@title='Sensitive']`,
    filtersProductsCheckBoxesCombinationLabel: `//label[text()='Combination']`,
    filtersProductsCheckBoxesDryLabel: `//label[text()='Dry']`,
    filtersProductsCheckBoxesNormalLabel: `//label[text()='Normal']`,
    filtersProductsCheckBoxesOilyLabel: `//label[text()='Oily']`,
    filtersProductsCheckBoxesSensitiveLabel: `//label[text()='Sensitive']`,

    filtersProductsCategoryUpArrow: `//h3[text()='Product Category']/following-sibling::span[@class='self-center arrow-upwards']`,
    filtersProductsCategoryDownArrow: `//h3[text()='Product Category']/following-sibling::span[@class='self-center arrow-downwards']`,
    filtersBestSellerUpArrow: `//h3[text()='Best Seller']/following-sibling::span[@class='self-center arrow-upwards']`,
    filtersBestSellerDownArrow: `//h3[text()='Best Seller']/following-sibling::span[@class='self-center arrow-downwards']`,
    filtersProductsTypeUpArrow: `//h3[text()='Product Types']/following-sibling::span[@class='self-center arrow-upwards']`,
    filtersProductsTypeDownArrow: `//h3[text()='Product Types']/following-sibling::span[@class='self-center arrow-downwards']`,
    filtersSkinConcernUpArrow: `//h3[text()='Skin Concern']/following-sibling::span[@class='self-center arrow-upwards']`,
    filtersSkinConcernDownArrow: `//h3[text()='Skin Concern']/following-sibling::span[@class='self-center arrow-downwards']`,
    filtersSkinTypeUpArrow: `//h3[text()='Skin Type']/following-sibling::span[@class='self-center arrow-upwards']`,
    filtersSkinTypeDownArrow: `//h3[text()='Skin Type']/following-sibling::span[@class='self-center arrow-downwards']`,

    filtersBestSellerCheckBoxesCount: `div.accordion__item:has-text("Best Seller") div.flex.py-2:has-text("Best Seller") div.font-light.text-tertiary-400`,
    filtersProductTypesBackbarCheckBoxesCount: `div.accordion__item:has-text("Product Types") div.flex.py-2:has-text("Backbar") div.font-light.text-tertiary-400`,
    filtersProductTypesRetailCheckBoxesCount: `div.accordion__item:has-text("Product Types") div.flex.py-2:has-text("Retail") div.font-light.text-tertiary-400`,
    filtersProductTypesSampleCheckBoxesCount: `div.accordion__item:has-text("Product Types") div.flex.py-2:has-text("Sample") div.font-light.text-tertiary-400`,
    filtersSkinConcernBrighteningCheckBoxesCount: `div.accordion__item:has-text("Skin Concern") div.flex.py-2:has-text("Brightening") div.font-light.text-tertiary-400`,
    filtersSkinConcernAcneCheckBoxesCount: `div.accordion__item:has-text("Skin Concern") div.flex.py-2:has-text("Acne") div.font-light.text-tertiary-400`,
    filtersSkinConcernAgingCheckBoxesCount: `div.accordion__item:has-text("Skin Concern") div.flex.py-2:has-text("Aging") div.font-light.text-tertiary-400`,
    filtersSkinConcernDiscolorationsCheckBoxesCount: `div.accordion__item:has-text("Skin Concern") div.flex.py-2:has-text("Discolorations") div.font-light.text-tertiary-400`,
    filtersSkinConcernPreventativeCheckBoxesCount: `div.accordion__item:has-text("Skin Concern") div.flex.py-2:has-text("Preventative") div.font-light.text-tertiary-400`,
    filtersSkinConcernSensitiveSkinCheckBoxesCount: `div.accordion__item:has-text("Skin Concern") div.flex.py-2:has-text("Sensitive Skin") div.font-light.text-tertiary-400`,
    filtersSkinTypeCombinationCheckBoxesCount: `div.accordion__item:has-text("Skin Type") div.flex.py-2:has-text("Combination") div.font-light.text-tertiary-400`,
    filtersSkinTypeDryCheckBoxesCount: `div.accordion__item:has-text("Skin Type") div.flex.py-2:has-text("Dry") div.font-light.text-tertiary-400`,
    filtersSkinTypeNormalCheckBoxesCount: `div.accordion__item:has-text("Skin Type") div.flex.py-2:has-text("Normal") div.font-light.text-tertiary-400`,
    filtersSkinTypeOilyCheckBoxesCount: `div.accordion__item:has-text("Skin Type") div.flex.py-2:has-text("Oily") div.font-light.text-tertiary-400`,
    filtersSkinTypeSensitiveCheckBoxesCount: `div.accordion__item:has-text("Skin Type") div.flex.py-2:has-text("Sensitive") div.font-light.text-tertiary-400`,



    pcaStudentOnlytextlabel: `//button[contains(@class,'focus-visible')]//div[text()='student-only']`,
    pcaStudentOnlyCloseBtn: `//button[contains(@class,'focus-visible')]//div[@class='cross-icon-active']`,
    pcaClearFilterBtn: `//button[contains(@class,'clear-filters')]`,

    pcatotalCountOfProducts: `//div[contains(@class,'sort-label')]//span`,
    pcaDropDown: `//div[contains(@data-testid,'sort-container')]//select[@id='sort-dropdown']`,
    pcaDropDownAlphabeticalAtoZ: `//div[contains(@data-testid,'sort-container')]//select[@id='sort-dropdown'] //option[text()='Alphabetical A - Z']`,
    pcaDropDownAlphabeticalZtoA: `//div[contains(@data-testid,'sort-container')]//select[@id='sort-dropdown'] //option[text()='Alphabetical Z - A']`,
    pcaDropDownPriceLowtoHigh: `//div[contains(@data-testid,'sort-container')]//select[@id='sort-dropdown'] //option[text()='Price Low to High']`,
    pcaDropDownPriceHightoLow: `//div[contains(@data-testid,'sort-container')]//select[@id='sort-dropdown'] //option[text()='Price High to Low']`,

    pcaBestSellerBedge: `//div[@class="product-grid"]//p[text()='Acne Cream']//ancestor::div[contains(@class,'product-card-main-wrapper')]//span[contains(@class,'best-seller badge')]`,
    pcaProductListAcneCream: `(//div[contains(@class,'product-card-content')]//div[contains(@class,'quick-view-btn-container')])[1]`,
    pcaproductListAcneGelwithOmniSome: `(//div[contains(@class,'product-card-content')]//div[contains(@class,'quick-view-btn-container')])[2]`,
    pcaproductListActiveBroadSpectrumSPF45: `(//div[contains(@class,'product-card-content')]//div[contains(@class,'quick-view-btn-container')])[3]`,
    pcaproductListAntiRednessSerum: `(//div[contains(@class,'product-card-content')]//div[contains(@class,'quick-view-btn-container')])[4]`,
    pcaproductListAprèsPeelHydratingBalm: `(//div[contains(@class,'product-card-content')]//div[contains(@class,'quick-view-btn-container')])[5]`,
    pcaproductListBlemishControlBar: `(//div[contains(@class,'product-card-content')]//div[contains(@class,'quick-view-btn-container')])[6]`,
    pcaproductListBodyTherapy: `(//div[contains(@class,'product-card-content')]//div[contains(@class,'quick-view-btn-container')])[7]`,
    pcaproductListBPO5perCleanser: `(//div[contains(@class,'product-card-content')]//div[contains(@class,'quick-view-btn-container')])[8]`,
    pcaproductListCandEAdvanced: `(//div[contains(@class,'product-card-content')]//div[contains(@class,'quick-view-btn-container')])[9]`,

    pcaproductListAcneCreamStarOrReview: `//div[contains(@class,'relative col-span-1')]//div[contains(@class,'mt-2 mb-2')]//div[@data-bv-product-id='10101']`,
    pcaproductListAcneGelwithOmniSomeStarOrReview: `//div[contains(@class,'relative col-span-1')]//div[contains(@class,'mt-2 mb-2')]//div[@data-bv-product-id='10123']`,
    pcaproductListActiveBroadSpectrumSPF45StarOrReview: `//div[contains(@class,'relative col-span-1')]//div[contains(@class,'mt-2 mb-2')]//div[@data-bv-product-id='10122']`,
    pcaproductListAntiRednessSerumStarOrReview: `//div[contains(@class,'relative col-span-1')]//div[contains(@class,'mt-2 mb-2')]//div[@data-bv-product-id='10080']`,
    pcaproductListAprèsPeelHydratingBalmStarOrReview: `//div[contains(@class,'relative col-span-1')]//div[contains(@class,'mt-2 mb-2')]//div[@data-bv-product-id='10093']`,
    pcaproductListBlemishControlBarStarOrReview: `//div[contains(@class,'relative col-span-1')]//div[contains(@class,'mt-2 mb-2')]//div[@data-bv-product-id='10102']`,
    pcaproductListBodyTherapyStarOrReview: `//div[contains(@class,'relative col-span-1')]//div[contains(@class,'mt-2 mb-2')]//div[@data-bv-product-id='10027']`,
    pcaproductListBPO5perCleanserStarOrReview: `//div[contains(@class,'relative col-span-1')]//div[contains(@class,'mt-2 mb-2')]//div[@data-bv-product-id='10100']`,
    pcaproductListCandEAdvancedStarOrReview: `//div[contains(@class,'relative col-span-1')]//div[contains(@class,'mt-2 mb-2')]//div[@data-bv-product-id='10001']`,


    pcaproductListAcneCreamLoginToOrderBtn: `//div[contains(@class,'flex justify-center pt-3 btns')]//button[contains(@aria-label,'Log in to order Acne Cream')]`,
    pcaproductListAcneGelwithOmniSomeLoginToOrderBtn: `//div[contains(@class,'flex justify-center pt-3 btns')]//button[contains(@aria-label,'Log in to order Acne Gel with OmniSome®')]`,
    pcaproductListActiveBroadSpectrumSPF45LoginToOrderBtn: `//div[contains(@class,'flex justify-center pt-3 btns')]//button[contains(@aria-label,'Log in to order Active Broad Spectrum SPF 45')]`,
    pcaproductListAntiRednessSerumLoginToOrderBtn: `//div[contains(@class,'flex justify-center pt-3 btns')]//button[contains(@aria-label,'Log in to order Anti-Redness Serum')]`,
    pcaproductListAprèsPeelHydratingBalmLoginToOrderBtn: `//div[contains(@class,'flex justify-center pt-3 btns')]//button[contains(@aria-label,'Log in to order Après Peel® Hydrating Balm')]`,
    pcaproductListBlemishControlBarLoginToOrderBtn: `//div[contains(@class,'flex justify-center pt-3 btns')]//button[contains(@aria-label,'Log in to order Blemish Control Bar')]`,
    pcaproductListBodyTherapyLoginToOrderBtn: `//div[contains(@class,'flex justify-center pt-3 btns')]//button[contains(@aria-label,'Log in to order Body Therapy v1')]`,
    pcaproductListBPO5perCleanserLoginToOrderBtn: `//div[contains(@class,'flex justify-center pt-3 btns')]//button[contains(@aria-label,'Log in to order BPO 5% Cleanser')]`,
    pcaproductListCandEAdvancedLoginToOrderBtn: `//div[contains(@class,'flex justify-center pt-3 btns')]//button[contains(@aria-label,'Log in to order C&E Advanced')]`,

    pcaViewingOutOfProducts: `//div[contains(@class,'mt-12')]//p[contains(text(),'Viewing ')]`,
    pcaloadMoreBtn: `//div[@aria-live="polite"]//button[text()='Load More']`,

    pcaRecentViewProductLabel: `//div[contains(@class,'product-carousel-title')]//h3[text()='Recently Viewed Products']`,
    pcaRecentViewProductLabelBedge: `//div[@id='swiper-wrapper-ba6a614a933f36ef']//div[contains(@class,'swiper-slide')] //div[contains(@class,'product-badge')]//span[contains(@class,'best-seller badge')]`,

    pcaRecentViewProductProductListAcneCream: `//div[contains(@class,'swiper-wrapper')]//div[contains(@class,'swiper-slide')]//div[contains(@aria-label,'Acne Cream false false')]`,
    pcaRecentViewProductProductListActiveBroadSpectrumSPF45: `//div[contains(@class,'swiper-wrapper')]//div[contains(@class,'swiper-slide')]//div[contains(@aria-label,'Active Broad Spectrum SPF 45 false false')]`,
    pcaRecentViewProductProductListHydraBright: `//div[contains(@class,'swiper-wrapper')]//div[contains(@class,'swiper-slide')]//div[contains(@aria-label,'HydraBright false false')]`,

    pcaRecentViewProductproductListAcneCreamStarOrReview: `//div[contains(@class,'swiper-wrapper')]//div[@data-bv-product-id='10101']`,
    pcaRecentViewProductproductListActiveBroadSpectrumSPF45StarOrReview: `//div[contains(@class,'swiper-wrapper')]//div[@data-bv-product-id='10122']`,
    pcaRecentViewProductproductListHydraBrightStarOrReview: `//div[contains(@class,'swiper-wrapper')]//div[@data-bv-product-id='10279']`,

    pcaRecentViewProductProductListAcneCreamLabel: `//div[contains(@class,'swiper-wrapper')]//p[text()='Acne Cream']`,
    pcaRecentViewProductProductListActiveBroadSpectrumSPF45Label: `//div[contains(@class,'swiper-wrapper')]//p[text()='Active Broad Spectrum SPF 45']`,
    pcaRecentViewProductProductListHydraBrightLabel: `//div[contains(@class,'swiper-wrapper')]//p[text()='HydraBright']`,

    pcaRecentViewProductProductListAcneCreamLogintoorder: `//div[contains(@class,'swiper-wrapper')]//button[@aria-label='Log in to Order Acne Cream']`,
    pcaRecentViewProductProductListActiveBroadSpectrumSPF45Logintoorder: `//div[contains(@class,'swiper-wrapper')]//button[@aria-label='Log in to Order Active Broad Spectrum SPF 45']`,
    pcaRecentViewProductProductListHydraBrightLogintoorder: `//div[contains(@class,'swiper-wrapper')]//button[@aria-label='Log in to Order HydraBright']`,

    pcaRecentViewProductcarouselRightactive: `//div[contains(@class,'swiper-button-next')]`,
    pcaRecentViewProductcarouselLeftactive: `//div[contains(@class,'swiper-button-prev')]`,
    pcaRecentViewProductcarouselRightinActive: `//div[contains(@class,'swiper-button-next swiper-button-disabled')]`,
    pcaRecentViewProductcarouselLeftinActive: `//div[contains(@class,'swiper-button-prev swiper-button-disabled')]`,


    // Login User
    pcafirstProductPrice: `div.product-grid div.mt-3.h-14.price-wrapper.false >> nth=0`,
    pcasecondProductPrice: `div.product-grid div.mt-3.h-14.price-wrapper.false >> nth=1`,
    pcathirdProductPrice: `div.product-grid div.mt-3.h-14.price-wrapper.false >> nth=2`,
    pcafourthProductPrice: `div.product-grid div.mt-3.h-14.price-wrapper.false >> nth=3`,
    pcafifthProductPrice: `div.product-grid div.mt-3.h-14.price-wrapper.false >> nth=4`,
    pcasixthProductPrice: `div.product-grid div.mt-3.h-14.price-wrapper.false >> nth=5`,
    pcaseventhProductPrice: `div.product-grid div.mt-3.h-14.price-wrapper.false >> nth=6`,
    pcaeightthProductPrice: `div.product-grid div.mt-3.h-14.price-wrapper.false >> nth=7`,
    pcaninethProductPrice: `div.product-grid div.mt-3.h-14.price-wrapper.false >> nth=8`,

    pcafirstProductFavouriteButton: `button.font-bold.text-sm.favorite-cta.favorite_favorite-button__XiNVR.false.primary.light.false >> nth=0`,
    pcasecondProductFavouriteButton: `button.font-bold.text-sm.favorite-cta.favorite_favorite-button__XiNVR.false.primary.light.false >> nth=1`,
    pcathirdProductFavouriteButton: `button.font-bold.text-sm.favorite-cta.favorite_favorite-button__XiNVR.false.primary.light.false >> nth=2`,
    pcafourthProductFavouriteButton: `button.font-bold.text-sm.favorite-cta.favorite_favorite-button__XiNVR.false.primary.light.false >> nth=3`,
    pcafifthProductFavouriteButton: `button.font-bold.text-sm.favorite-cta.favorite_favorite-button__XiNVR.false.primary.light.false >> nth=4`,
    pcasixthProductFavouriteButton: `button.font-bold.text-sm.favorite-cta.favorite_favorite-button__XiNVR.false.primary.light.false >> nth=5`,
    pcaseventhProductFavouriteButton: `button.font-bold.text-sm.favorite-cta.favorite_favorite-button__XiNVR.false.primary.light.false >> nth=6`,
    pcaeightthProductFavouriteButton: `button.font-bold.text-sm.favorite-cta.favorite_favorite-button__XiNVR.false.primary.light.false >> nth=7`,
    pcaninethProductFavouriteButton: `button.font-bold.text-sm.favorite-cta.favorite_favorite-button__XiNVR.false.primary.light.false >> nth=8`,

    pcaFirstAddtocartBtn: `(//div[contains(@class,'product-list')]//button[@aria-label='Add to Cart'])[1]`,
    pcaSecondAddtocartBtn: `(//div[contains(@class,'product-list')]//button[@aria-label='Add to Cart'])[2]`,
    pcaThirdAddtocartBtn: `(//div[contains(@class,'product-list')]//button[@aria-label='Add to Cart'])[3]`,
    pcaFourthAddtocartBtn: `(//div[contains(@class,'product-list')]//button[@aria-label='Add to Cart'])[4]`,
    pcaFifthAddtocartBtn: `(//div[contains(@class,'product-list')]//button[@aria-label='Add to Cart'])[5]`,
    pcaSixthAddtocartBtn: `(//div[contains(@class,'product-list')]//button[@aria-label='Add to Cart'])[6]`,

    pcaFirstSelectSizeBtn: `(//div[contains(@class,'product-list')]//a[contains(@class,'bg-transparent ')])[1]`,
    pcaSecondSelectSizeBtn: `(//div[contains(@class,'product-list')]//a[contains(@class,'bg-transparent ')])[2]`,
    pcaThirdSelectSizeBtn: `(//div[contains(@class,'product-list')]//a[contains(@class,'bg-transparent ')])[3]`,

    pcaFirstQuickViewBtn: `(//div[contains(@class,'product-list')]//button[contains(@aria-label,'Quick View')])[1]`,
    pcaSecondQuickViewBtn: `(//div[contains(@class,'product-list')]//button[contains(@aria-label,'Quick View')])[2]`,
    pcaThirdQuickViewBtn: `(//div[contains(@class,'product-list')]//button[contains(@aria-label,'Quick View')])[3]`,
    pcaFourthQuickViewBtn: `(//div[contains(@class,'product-list')]//button[contains(@aria-label,'Quick View')])[4]`,
    pcaFifthQuickViewBtn: `(//div[contains(@class,'product-list')]//button[contains(@aria-label,'Quick View')])[5]`,
    pcaSixthQuickViewBtn: `(//div[contains(@class,'product-list')]//button[contains(@aria-label,'Quick View')])[6]`,
    pcaSeventhQuickViewBtn: `(//div[contains(@class,'product-list')]//button[contains(@aria-label,'Quick View')])[7]`,
    pcaEightQuickViewBtn: `(//div[contains(@class,'product-list')]//button[contains(@aria-label,'Quick View')])[8]`,
    pcaNineQuickViewBtn: `(//div[contains(@class,'product-list')]//button[contains(@aria-label,'Quick View')])[9]`,

    //For Unauthenticated User Student Only 
    studentMenu: `//li[contains(@class,'navigation-menu-list')]//button[text()='Student']`,
    studentOnlyViewAll: `//div[contains(@class,'navigation-submenu')]//a[@aria-label='View All : Student Products']`,
    studentOnlyFilterAppliedLabel: `//button[contains(@class,'focus-visible')]//div[text()='student-only']`,
    studentOnlyProductImageAcneCream: `(//div[contains(@class,'product-card-content')]//div[contains(@class,'quick-view-btn-container')])[1]`,
    RedirectStudentOnlyDetailPage: `//div[contains(@class,'product-info')]//h1[contains(text(),'Acne Cream')]`,
    breadCrumbAllProduct: `//ul[contains(@class,'breadcrumb-label')]//a[contains(text(),'All Products')]`,
    breadcrumbForPDP: `//ul[contains(@class,'breadcrumb-label')]//span[contains(text(),'Acne Cream')]`,
    recentviewProductCard: `(//div[contains(@class,'swiper-wrapper')]//div[contains(@aria-label,'Acne Cream')])[1]`,
    favouriteIconStudentOnly: `(//div[contains(@class,'fav-compar')]//button[contains(@class,'favorite-button')])[1]`,

    loginToOrderBtnStudentOnly: `//div[contains(@class,'flex justify-center pt-3 btns')]//button[contains(@aria-label,'Log in to order Acne Cream')]`,
    loginDialogBoxStudentOnly: `//div[contains(@class,'sign-in-modal')]//div[contains(@id,'login-container')]//h1[contains(text(),'Customer Login')]`,
    quickViewBtnPlpPageStudentOnly: `(//div[contains(@class,'img-wrapper ')]//button[contains(@aria-label,'Quick View')])[1]`,

    productPriceOfCard: `(//div[contains(@class,'product-list')]//div[contains(@class,'price-wrapper')])[1]`,
    productFavouriteUnFavouriteOfCard: `(//div[contains(@class,'fav-compar')]//button[contains(@class,'favorite-button')])[1]`,
    productAddToCartButtonOfCard: `//div[@class="product-grid"]//p[text()='Acne Cream']//ancestor::div[contains(@class,'product_card group')]//button[text()='Add to Cart']`,
    productSelectSizeButtonOfCard: `(//div[contains(@class,'product-card')]//a[contains(text(),'Select Size')])[1]`,

    productPriceStudentOnlyRecentViewd: `(//div[contains(@id,'swiper-wrapper')]//div[contains(@aria-label,'Acne Cream')])//div[contains(@class,'price-wrapper')]`,
    notifyMeBtnStudentOnlyRecentViewed: `(//div[contains(@aria-label,'Hyaluronic Acid Overnight Mask')]//button[contains(text(),'Notify Me')])[1]`,
    addtoCartBtnStudentOnlyRecentViewd: `//div[contains(@id,'swiper-wrapper')]//div[contains(@aria-label,'Acne Cream')]//button[contains(@aria-label,'Add to Cart')]`,//Change Product name in aria label to other product
    selectSizeBtnStudentOnlyRecentViewd: `(//div[contains(@id,'swiper-wrapper')]//div[contains(@aria-label,'Acne Gel with OmniSome®')]//a[contains(text(),'Select Size')])[1]`,
    loginToOrderBtnStudentOnlyRecentView: `//div[contains(@aria-label,'Acne Cream ')]//button[contains(@aria-label,'Log in to Order')]`, //Change Product name in aria label to other product

    loadMoreBtnStudentOnly: `//div[contains(@class,'load_more')]//button[contains(text(),'Load More')]`,
    productscountBeforeClickLoadMoreStudentOnly: `//div[contains(@class,'load_more')]//p[contains(text(),'Viewing 9 out of 69 products')]`,
    productscountAfterClickLoadMoreStudentOnly: `//div[contains(@class,'load_more')]//p[contains(text(),'Viewing 18 out of 69 products')]`,

    pleaseWaitButton: `//div[contains(@class,'load_more')]//button[contains(text(),'Please wait...')]`,

    //StudentOnlyProductsLocators.ts
}