export const SubscriptionsLocators={
    pcaLeftMenuSubsription:`//div[contains(@class,'left-nav-menu-items')] // button[contains(@class,'text-secondary')]//span[text()='Subscriptions']`,
    pcaSubscriptionheader:`//div[contains(@class,'w-full col-span-12')] // h2[contains(@class,'heading')]`,
    
    pcaSubscriptionDetailsProductName:`//div[contains(@class,'w-full col-span-12')]//div[contains(@class,'subscription-details')]//div[contains(@class,'product-name')]`,
    pcaSubscriptionDetailsProductImage:`//div[contains(@class,'w-full col-span-12')]//div[contains(@class,'subscription-details')]//img`,
    pcaSubscriptionDetailsProductCode:`//div[contains(@class,'product-info')]//span[contains(text(),'Item#')]`,
    pcaSubscriptionDetailsProductPrice:`//div[contains(@class,'w-full col-span-12')]//div[contains(@class,'subscription-details')]//div[contains(@class,'product-info')]//p`,
   
    pcaSubscriptionDetailsCancelBtn:`//div[contains(@class,'w-full col-span-12')]//div[contains(@class,'action-section')]//div[contains(@class,'border-tertiary')]//button[contains(@class,'subscription_cancel')]`,
    pcaSubscriptionDetailsPauseBtn:`//div[contains(@class,'w-full col-span-12')]//div[contains(@class,'action-section')]//div[contains(@class,'border-tertiary')]//button[contains(@class,'subscription_pause')]`,
    
    pcaSubscriptionDetailsErrorMessage:` //div[contains(@class,'w-full col-span-12')]//div[contains(@class,'error-msg')]//div[text()='Unable to fetch the subscription  products. Please try after sometime']`,
    
    pcaSubscriptionDetailsUnabletofetchshippingaddressToast:`//div[contains(@class,'Toastify__toast')]//div[contains(@id,'autoshipment-shipping-address-error')]`,
    pcaSubscriptionDetailsUnabletofetchshippingaddressToastText:`//div[contains(@class,'Toastify__toast-body')]//div[contains(text(),'Unable to fetch shipping address')]`,
    pcaSubscriptionDetailsUnabletofetchshippingaddressToastCloseBtn:`//div[contains(@class,'Toastify__toast')]//div[contains(@id,'autoshipment-shipping-address-error')]//button[contains(@class,'Toastify__close-button')]`,
    
    pcaSubscriptionDetailsItemQuantityLabel:`//div[contains(@class,'w-full col-span-12')]//div[contains(@class,'selector')]//div[contains(@class,'qty-selector')]//label`,
    pcaSubscriptionDetailsItemQuantityDecreaseQtyBtn:`//div[contains(@class,'w-full col-span-12')]//div[contains(@class,'selector')]//div[contains(@class,'qty-selector')]//button[@aria-label='decrease quantity by 1']`,
    pcaSubscriptionDetailsItemQuantityIncreaseQtyBtn:`//div[contains(@class,'w-full col-span-12')]//div[contains(@class,'selector')]//div[contains(@class,'qty-selector')]//button[@aria-label='increase quantity by 1']`,
    pcaSubscriptionDetailsItemQuantityInputs:`//div[contains(@class,'w-full col-span-12')]//div[contains(@class,'selector')]//div[contains(@class,'qty-selector')]//input[@id='_itemQty']`,
    
    pcaSubscriptionDetailsFrequencyLabel:`//div[contains(@class,'w-full col-span-12')]//div[contains(@class,'frequency-wrapper')]//label`,
    pcaSubscriptionDetailsFrequencyDropDown:`//select[contains(@id,'frequency')]`,
    pcaSubscriptionDetailsFrequencyDropDown1Day:` //select[contains(@id,'frequency')]//option[text()='1 day']`,
    pcaSubscriptionDetailsFrequencyDropDown2Days:` //select[contains(@id,'frequency')]//option[text()='2 days']`,
    pcaSubscriptionDetailsFrequencyDropDown1Months:` //select[contains(@id,'frequency')]//option[text()='1 month']`,
    pcaSubscriptionDetailsFrequencyDropDown3Months:` //select[contains(@id,'frequency')]//option[text()='3 months']`,
    pcaSubscriptionDetailsFrequencyDropDown6Months:` //select[contains(@id,'frequency')]//option[text()='6 months']`,

    pcaFilterSubscriptionTitle:`//div[contains(@class,'w-full col-span-12')] //div[contains(@class,'filter-wrapper')]//div[contains(@class,'title')]`,    
   
    pcaLocationsDropDown:` //select[@id='address-filter']`,
    pcaLocationsDropDownValueAllLocations:` //select[@id='address-filter']//option[text()='All locations']`,
    pcaLocationsDropDownValue24CommercialStreet92101:` //select[@id='address-filter']//option[text()='24 Commercial Street 92101']`,
    
    pcaCategoriesDropDown:`//select[@id='category-filter']`,
    pcaCategoriesDropDownValueAllcategories:`//select[@id='category-filter']//option[text()='All categories']`,
    pcaCategoriesDropDownValueAntioxidants:`//select[@id='category-filter']//option[text()='Antioxidants']`,
    pcaCategoriesDropDownValueBroadSpectrumSPF:`//select[@id='category-filter']//option[text()='Broad Spectrum SPF']`,
    pcaCategoriesDropDownValueCleansersAndToners:`//select[@id='category-filter']//option[text()='Cleansers & Toners']`,
    pcaCategoriesDropDownValueEyeNeckLip:` //select[@id='category-filter']//option[text()='Eye, Neck, Lip']`,
    pcaCategoriesDropDownValueMasks:` //select[@id='category-filter']//option[text()='Masks']`,
    pcaCategoriesDropDownValueMoisturizers:` //select[@id='category-filter']//option[text()='Moisturizers']`,
    pcaCategoriesDropDownValueRetinols:` //select[@id='category-filter']//option[text()='Retinols']`,
    pcaCategoriesDropDownValueSerums:` //select[@id='category-filter']//option[text()='Serums']`,
    pcaCategoriesDropDownValueSolutionSets:` //select[@id='category-filter']//option[text()='Solution Sets']`,
    pcaCategoriesDropDownValuePeels:` //select[@id='category-filter']//option[text()='Peels']`,
    pcaCategoriesDropDownValuePeelAlternative:` //select[@id='category-filter']//option[text()='Peel Alternative']`,
    pcaCategoriesDropDownValueRetinoidTreatments:` //select[@id='category-filter']//option[text()='Retinoid Treatments']`,
    pcaCategoriesDropDownValueTherapeuticMasks:` //select[@id='category-filter']//option[text()='Therapeutic Masks']`,
    pcaCategoriesDropDownValueTreatmentEnhancements:` //select[@id='category-filter']//option[text()='Treatment Enhancements']`,
    pcaCategoriesDropDownValueBackbarSizes:` //select[@id='category-filter']//option[text()='Backbar Sizes']`,
    pcaCategoriesDropDownValueBackbarTools:` //select[@id='category-filter']//option[text()='Backbar Tools']`,
    pcaCategoriesDropDownValueBodyTreatments:` //select[@id='category-filter']//option[text()='Body Treatments']`,
    pcaCategoriesDropDownValueExfoliants:` //select[@id='category-filter']//option[text()='Exfoliants']`,
    pcaCategoriesDropDownValueFaceSunscreen:` //select[@id='category-filter']//option[text()='Face Sunscreen']`,
    pcaCategoriesDropDownValueFullBodySunscreen:` //select[@id='category-filter']//option[text()='Full Body Sunscreen']`,
    pcaCategoriesDropDownValueTintedSunscreen:` //select[@id='category-filter']//option[text()='Tinted Sunscreen']`,
    pcaCategoriesDropDownValueWaterResistantSunscreen:` //select[@id='category-filter']//option[text()='Water-Resistant Sunscreen']`,
    pcaCategoriesDropDownValuePostProcedure:` //select[@id='category-filter']//option[text()='Post Procedure']`,
    pcaCategoriesDropDownValueCleansers:` //select[@id='category-filter']//option[text()='Cleansers']`,
    pcaCategoriesDropDownValueFaceMoisturizers:` //select[@id='category-filter']//option[text()='Face Moisturizers']`,
    pcaCategoriesDropDownValueTreamentsampSerums:` //select[@id='category-filter']//option[text()='Treaments &amp; Serums']`,

    pcaUpdateSubscriptionButton:`//div[contains(@class,'action-section')]//div[contains(@class,'lg:flex')]//button[text()='Update Subscription']`,
    pcaScrollbacktotop:`//div[@id="__next"]//following::button[contains(@class,'fixed scroll-top-btn')]`,
    pcaYourNextShipmentMessage:`//div[contains(@class,'selector justify')]//div[contains(@class,'small ship-info')]`,
}
